package FRMs.registroAsistencia;

import com.mycompany.presentacion.ControlNavegacion;
import java.awt.Color;
import java.awt.Graphics;
import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JPanel;
import org.netbeans.lib.awtextra.AbsoluteConstraints;
import org.netbeans.lib.awtextra.AbsoluteLayout;

/**
 *
 * @author daniel
 */
public class FrmBuscarClase extends javax.swing.JFrame {

    private Image imagenFondo;

    public FrmBuscarClase() {
        initComponents();
        this.txtNombreClase.setForeground(Color.GRAY);
        this.txtNombreClase.setText("ingresa nombre clase...");
        this.setTitle("Buscar Clase");

        this.imagenFondo = new ImageIcon(getClass().getResource("/Utilerias/FondoCERO.jpeg")).getImage();

        JPanel pnlFondo = new javax.swing.JPanel() {
            @Override
            protected void paintComponent(Graphics g) {
                super.paintComponent(g);
                g.drawImage(imagenFondo, 0, 0, getWidth(), getHeight(), this);
            }
        };

        getContentPane().setLayout(new AbsoluteLayout());
        pack();
        getContentPane().add(pnlFondo, new AbsoluteConstraints(0, 0, getWidth(), getHeight()));
        this.setLocationRelativeTo(null);

    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the FormEditor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txtNombreClase = new javax.swing.JTextField();
        btnBuscarClase = new javax.swing.JButton();
        btnRegresar = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(148, 197, 227));
        setPreferredSize(new java.awt.Dimension(1280, 832));
        getContentPane().setLayout(null);

        jLabel9.setFont(new java.awt.Font("Menlo", 1, 24)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(30, 47, 86));
        jLabel9.setText("Nombre de la clase");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(490, 350, 280, 62);

        jLabel10.setFont(new java.awt.Font("Menlo", 1, 55)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(30, 47, 86));
        jLabel10.setText("CONTROL DE ASISTENCIAS");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(260, 140, 750, 65);

        txtNombreClase.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        txtNombreClase.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtNombreClase.setBorder(null);
        txtNombreClase.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtNombreClaseMouseClicked(evt);
            }
        });
        getContentPane().add(txtNombreClase);
        txtNombreClase.setBounds(330, 420, 580, 50);

        btnBuscarClase.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Utilerias/botones/btnBuscarClase.png"))); // NOI18N
        btnBuscarClase.setBorderPainted(false);
        btnBuscarClase.setContentAreaFilled(false);
        btnBuscarClase.setFocusPainted(false);
        btnBuscarClase.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarClaseActionPerformed(evt);
            }
        });
        getContentPane().add(btnBuscarClase);
        btnBuscarClase.setBounds(390, 540, 470, 90);

        btnRegresar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Utilerias/botones/btnRegresarGrande.png"))); // NOI18N
        btnRegresar.setBorderPainted(false);
        btnRegresar.setContentAreaFilled(false);
        btnRegresar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnRegresar.setFocusPainted(false);
        btnRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegresarActionPerformed(evt);
            }
        });
        getContentPane().add(btnRegresar);
        btnRegresar.setBounds(420, 630, 420, 80);

        jLabel3.setFont(new java.awt.Font("Menlo", 1, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(30, 47, 86));
        jLabel3.setText("Visualizar asistencias");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(370, 250, 500, 43);
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresarActionPerformed
        ControlNavegacion.mostrarSeleccionarOpcionAsistencia();
        this.dispose();
    }//GEN-LAST:event_btnRegresarActionPerformed


    private void btnBuscarClaseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarClaseActionPerformed
        ControlNavegacion.mostrarClasesExistentes(txtNombreClase.getText(), this);
        this.dispose();

    }//GEN-LAST:event_btnBuscarClaseActionPerformed

    private void txtNombreClaseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtNombreClaseMouseClicked
        txtNombreClase.setText("");
        txtNombreClase.setForeground(Color.BLACK);

    }//GEN-LAST:event_txtNombreClaseMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscarClase;
    private javax.swing.JButton btnRegresar;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField txtNombreClase;
    // End of variables declaration//GEN-END:variables
}
