package FRMs.registroAsistencia;

import DTOs.GestionarClases.ClaseListaDTO;
import com.itextpdf.text.BaseColor;
import com.itextpdf.text.Chunk;
import com.itextpdf.text.Document;
import com.itextpdf.text.Element;
import com.itextpdf.text.Font;
import com.itextpdf.text.FontFactory;
import com.itextpdf.text.Paragraph;
import com.itextpdf.text.Phrase;
import com.itextpdf.text.pdf.PdfPCell;
import com.itextpdf.text.pdf.PdfPTable;
import com.itextpdf.text.pdf.PdfWriter;
import com.mycompany.dtos.ReporteAsistenciaDTO;
import com.mycompany.presentacion.ControlNavegacion;
import java.awt.Color;
import java.awt.Desktop;
import java.awt.Graphics;
import java.awt.Image;
import java.io.File;
import java.io.FileOutputStream;
import java.time.LocalDate;
import java.time.ZoneId;
import java.time.format.DateTimeFormatter;
import java.util.Date;
import java.util.List;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
import org.netbeans.lib.awtextra.AbsoluteConstraints;
import org.netbeans.lib.awtextra.AbsoluteLayout;

/**
 *
 * @author daniel
 */
public class FrmReporteAsistencias extends javax.swing.JFrame {

    private Image imagenFondo;
    private ClaseListaDTO claseDTO;

    public FrmReporteAsistencias(ClaseListaDTO claseDTO) {
        initComponents();
        this.setTitle("Reporte de asistencias");
        this.claseDTO = claseDTO;

        this.imagenFondo = new ImageIcon(getClass().getResource("/Utilerias/FondoCERO.jpeg")).getImage();

        JPanel pnlFondo = new javax.swing.JPanel() {
            @Override
            protected void paintComponent(Graphics g) {
                super.paintComponent(g);
                g.drawImage(imagenFondo, 0, 0, getWidth(), getHeight(), this);
            }
        };

        getContentPane().setLayout(new AbsoluteLayout());
        pack();
        getContentPane().add(pnlFondo, new AbsoluteConstraints(0, 0, getWidth(), getHeight()));
        this.setLocationRelativeTo(null);
        this.setDefaultCloseOperation(EXIT_ON_CLOSE);

    }

    private void llenarTabla(List<ReporteAsistenciaDTO> reportes) {
        if (reportes == null) {
            return;
        }

        DefaultTableModel modeloTabla = (DefaultTableModel) this.tblReporte.getModel();
        if (modeloTabla.getRowCount() > 0) {
            for (int i = modeloTabla.getRowCount() - 1; i > -1; i--) {
                modeloTabla.removeRow(i);
            }
        }
        reportes.forEach(row -> {
            Object[] fila = new Object[5];
            fila[0] = row.getIdAlumno();
            fila[1] = row.getNombre();
            fila[2] = row.getFechaClase();
            fila[3] = row.getTipoAsistencia().toString();
            fila[4] = row.getJustificante();

            modeloTabla.addRow(fila);
        });
    }

    private void cargarDatos() {
        Integer idAlumno = null;
        if (!txtIdAlumno.getText().isEmpty()) {
            try {
                idAlumno = Integer.valueOf(this.txtIdAlumno.getText());
            } catch (NumberFormatException e) {
                JOptionPane.showMessageDialog(this, "El ID del alumno no es válido.", "Error", JOptionPane.ERROR_MESSAGE);
                return;
            }
        }

        Date inicio = this.fechaInicio.getDate();
        Date fin = this.fechaFin.getDate();
        
        LocalDate fechaInicio = inicio.toInstant().atZone(ZoneId.systemDefault()).toLocalDate();
        LocalDate fechaFin = fin.toInstant().atZone(ZoneId.systemDefault()).toLocalDate();

        List<ReporteAsistenciaDTO> reportes;
        if (idAlumno == null) {

            reportes = ControlNavegacion.obtenerReportesAsistencia(claseDTO.getCodigo(), null, fechaInicio, fechaFin);
        } else {
            reportes = ControlNavegacion.obtenerReportesAsistencia(claseDTO.getCodigo(), idAlumno, fechaInicio, fechaFin);
        }
        llenarTabla(reportes);
    }

    private void addTableHeader(PdfPTable table, String text, Font font) {
        PdfPCell cell = new PdfPCell(new Phrase(text, font));
        cell.setBackgroundColor(new BaseColor(65, 70, 105));
        cell.setPadding(5);
        cell.setHorizontalAlignment(Element.ALIGN_CENTER);
        table.addCell(cell);
    }

    private void addTableCell(PdfPTable table, String text) {
        addTableCell(table, text, Element.ALIGN_LEFT);
    }

    private void addTableCell(PdfPTable table, String text, int alignment) {
        PdfPCell cell = new PdfPCell(new Phrase(text));
        cell.setPadding(5);
        cell.setHorizontalAlignment(alignment);
        table.addCell(cell);
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the FormEditor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txtIdAlumno = new javax.swing.JTextField();
        btnGenerarReporte = new javax.swing.JButton();
        fechaFin = new com.toedter.calendar.JDateChooser();
        fechaInicio = new com.toedter.calendar.JDateChooser();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblReporte = new javax.swing.JTable();
        btnRegresar = new javax.swing.JButton();
        btnGuardarReporte = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(148, 197, 227));
        setPreferredSize(new java.awt.Dimension(1280, 832));
        getContentPane().setLayout(null);

        jLabel9.setFont(new java.awt.Font("Menlo", 1, 24)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(30, 47, 86));
        jLabel9.setText("a");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(710, 160, 30, 40);

        jLabel10.setFont(new java.awt.Font("Menlo", 1, 24)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(30, 47, 86));
        jLabel10.setText("Fecha");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(540, 100, 210, 65);

        txtIdAlumno.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        txtIdAlumno.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtIdAlumno.setBorder(null);
        txtIdAlumno.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtIdAlumnoMouseClicked(evt);
            }
        });
        getContentPane().add(txtIdAlumno);
        txtIdAlumno.setBounds(120, 160, 300, 40);

        btnGenerarReporte.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Utilerias/botones/btnGenerarReporte.png"))); // NOI18N
        btnGenerarReporte.setBorderPainted(false);
        btnGenerarReporte.setContentAreaFilled(false);
        btnGenerarReporte.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnGenerarReporte.setFocusPainted(false);
        btnGenerarReporte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGenerarReporteActionPerformed(evt);
            }
        });
        getContentPane().add(btnGenerarReporte);
        btnGenerarReporte.setBounds(950, 140, 220, 70);
        getContentPane().add(fechaFin);
        fechaFin.setBounds(740, 160, 150, 40);
        getContentPane().add(fechaInicio);
        fechaInicio.setBounds(540, 160, 150, 40);

        tblReporte.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID alumno", "Nombre", "Fecha clase", "Asistencia", "Justificación"
            }
        ));
        tblReporte.setPreferredSize(new java.awt.Dimension(450, 400));
        tblReporte.setSize(new java.awt.Dimension(450, 400));
        jScrollPane1.setViewportView(tblReporte);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(50, 230, 1200, 480);

        btnRegresar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Utilerias/botones/btnRegresar.png"))); // NOI18N
        btnRegresar.setBorderPainted(false);
        btnRegresar.setContentAreaFilled(false);
        btnRegresar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnRegresar.setFocusPainted(false);
        btnRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegresarActionPerformed(evt);
            }
        });
        getContentPane().add(btnRegresar);
        btnRegresar.setBounds(300, 710, 330, 80);

        btnGuardarReporte.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Utilerias/botones/btnGuardarReporte.png"))); // NOI18N
        btnGuardarReporte.setBorderPainted(false);
        btnGuardarReporte.setContentAreaFilled(false);
        btnGuardarReporte.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnGuardarReporte.setFocusPainted(false);
        btnGuardarReporte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarReporteActionPerformed(evt);
            }
        });
        getContentPane().add(btnGuardarReporte);
        btnGuardarReporte.setBounds(660, 710, 330, 80);

        jLabel11.setFont(new java.awt.Font("Menlo", 1, 55)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(30, 47, 86));
        jLabel11.setText("REPORTE DE ASISTENCIAS");
        getContentPane().add(jLabel11);
        jLabel11.setBounds(290, 40, 750, 65);

        jLabel12.setFont(new java.awt.Font("Menlo", 1, 24)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(30, 47, 86));
        jLabel12.setText("Id del alumno:");
        getContentPane().add(jLabel12);
        jLabel12.setBounds(120, 100, 210, 65);
    }// </editor-fold>//GEN-END:initComponents

    private void btnGenerarReporteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGenerarReporteActionPerformed
        Date actual = new Date();
        if (fechaInicio.getDate() == null || fechaFin.getDate() == null) {
            JOptionPane.showMessageDialog(null, "Se debe de seleccionar una fecha", "Error", JOptionPane.ERROR_MESSAGE);
        } else if (fechaInicio.getDate().after(actual)) {
            JOptionPane.showMessageDialog(null, "La fecha de inicio del rango no puede estar después de la fecha actual.", "Error", JOptionPane.ERROR_MESSAGE);
        } else {
            cargarDatos();
        }
    }//GEN-LAST:event_btnGenerarReporteActionPerformed


    private void txtIdAlumnoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtIdAlumnoMouseClicked

        txtIdAlumno.setText("");
        txtIdAlumno.setForeground(Color.BLACK);

    }//GEN-LAST:event_txtIdAlumnoMouseClicked

    private void btnRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresarActionPerformed
        ControlNavegacion.mostrarBuscarClaseReporte();
        this.dispose();
    }//GEN-LAST:event_btnRegresarActionPerformed

    private void btnGuardarReporteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarReporteActionPerformed
        String path = "";
        JFileChooser j = new JFileChooser();
        j.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
        int x = j.showSaveDialog(this);

        if (x == JFileChooser.APPROVE_OPTION) {
            File selectedDir = j.getSelectedFile();
            if (selectedDir != null && selectedDir.isDirectory()) {
                path = selectedDir.getAbsolutePath();
            }
        }

        if (path.isEmpty()) {
            JOptionPane.showMessageDialog(this, "No se seleccionó ninguna carpeta.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        String fullPath = path + File.separator + "CERO_ReporteAsistencias.pdf";
        System.out.println("Ruta seleccionada: " + fullPath);
        File file = new File(fullPath);
        Document doc = new Document();

        try {
            PdfWriter.getInstance(doc, new FileOutputStream(file));
            doc.open();

            Font titleFont = FontFactory.getFont(FontFactory.HELVETICA_BOLD, 18, new BaseColor(65, 70, 105));
            Font headerFont = FontFactory.getFont(FontFactory.HELVETICA_BOLD, 12, BaseColor.WHITE);
            Font totalFont = FontFactory.getFont(FontFactory.HELVETICA_BOLD, 14, new BaseColor(227, 148, 147));
            Font subtitleFont = FontFactory.getFont(FontFactory.HELVETICA, 12, BaseColor.DARK_GRAY);

            Paragraph title = new Paragraph("Reporte de Asistencias por alumno", titleFont);
            title.setAlignment(Element.ALIGN_CENTER);
            doc.add(title);

            DateTimeFormatter formatoFecha = DateTimeFormatter.ofPattern("dd-MM-yyyy");

            Date fechaInicioDate = fechaInicio.getDate();
            Date fechaFinDate = fechaFin.getDate();

            LocalDate localFechaInicio = fechaInicioDate.toInstant().atZone(ZoneId.systemDefault()).toLocalDate();
            LocalDate localFechaFin = fechaFinDate.toInstant().atZone(ZoneId.systemDefault()).toLocalDate();

            String fechaInicioFormateada = localFechaInicio.format(formatoFecha);
            String fechaFinFormateada = localFechaFin.format(formatoFecha);

            Paragraph valores = new Paragraph();
            valores.setAlignment(Element.ALIGN_CENTER);
            valores.setFont(subtitleFont);

            valores.add(new Chunk("ID del alumno: ", FontFactory.getFont(FontFactory.HELVETICA_BOLD, 12, BaseColor.BLUE)));
            valores.add(new Chunk(txtIdAlumno.getText() + "\n", FontFactory.getFont(FontFactory.HELVETICA, 12, BaseColor.BLACK)));

            valores.add(new Chunk("Clase: ", FontFactory.getFont(FontFactory.HELVETICA_BOLD, 12, BaseColor.BLUE)));
            valores.add(new Chunk(claseDTO.getNombreClase() + "\n", FontFactory.getFont(FontFactory.HELVETICA, 12, BaseColor.BLACK)));

            valores.add(new Chunk("Fechas: ", FontFactory.getFont(FontFactory.HELVETICA_BOLD, 12, BaseColor.BLUE)));
            valores.add(new Chunk(fechaInicioFormateada + " a " + fechaFinFormateada, FontFactory.getFont(FontFactory.HELVETICA, 12, BaseColor.BLACK)));
            valores.setAlignment(Element.ALIGN_CENTER);
            doc.add(valores);
            doc.add(Chunk.NEWLINE);

            PdfPTable tbl = new PdfPTable(5);
            tbl.setWidthPercentage(100);
            tbl.setSpacingBefore(15f);
            tbl.setSpacingAfter(15f);

            float[] columnWidths = {1.2f, 2.5f, 1.5f, 2f, 1.5f};
            tbl.setWidths(columnWidths);

            addTableHeader(tbl, "ID alumno", headerFont);
            addTableHeader(tbl, "Nombre", headerFont);
            addTableHeader(tbl, "Fecha de clase", headerFont);
            addTableHeader(tbl, "Asistencia", headerFont);
            addTableHeader(tbl, "Justificante", headerFont);

            for (int i = 0; i < tblReporte.getRowCount(); i++) {
                addTableCell(tbl, tblReporte.getValueAt(i, 0).toString());
                addTableCell(tbl, tblReporte.getValueAt(i, 1).toString());
                addTableCell(tbl, tblReporte.getValueAt(i, 2).toString());
                addTableCell(tbl, tblReporte.getValueAt(i, 3).toString());
                addTableCell(tbl, tblReporte.getValueAt(i, 4).toString());

            }

            doc.add(tbl);

            JOptionPane.showMessageDialog(this, "Documento generado con éxito!");

        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Error: " + ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        } finally {
            if (doc != null && doc.isOpen()) {
                doc.close();
            }
        }

        if (Desktop.isDesktopSupported() && file.exists()) {
            try {
                Desktop.getDesktop().open(file);
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(this,
                        "El PDF se generó pero no se pudo abrir: " + ex.getMessage(),
                        "Aviso",
                        JOptionPane.WARNING_MESSAGE);
            }
        }
    }//GEN-LAST:event_btnGuardarReporteActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGenerarReporte;
    private javax.swing.JButton btnGuardarReporte;
    private javax.swing.JButton btnRegresar;
    private com.toedter.calendar.JDateChooser fechaFin;
    private com.toedter.calendar.JDateChooser fechaInicio;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblReporte;
    private javax.swing.JTextField txtIdAlumno;
    // End of variables declaration//GEN-END:variables
}
