
package FRMs.registroAsistencia;

import FRMs.*;
import com.mycompany.presentacion.ControlNavegacion;
import java.awt.Graphics;
import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JPanel;
import org.netbeans.lib.awtextra.AbsoluteConstraints;
import org.netbeans.lib.awtextra.AbsoluteLayout;

/**
 *
 * @author Usuario
 */
public class FrmRegistrarAsistenciaActualAlumno extends javax.swing.JFrame {
    private Image imagenFondo;
    private ControlNavegacion controlNav;

    /**
     * Creates new form FrmMenuPrincipal
     */
    public FrmRegistrarAsistenciaActualAlumno() {
        initComponents();
        this.setTitle("Registrar asistencia individual");
        
        this.imagenFondo = new ImageIcon(getClass().getResource("/Utilerias/FondoCERO.jpeg")).getImage();

        JPanel pnlFondo = new javax.swing.JPanel() {
            @Override
            protected void paintComponent(Graphics g) {
                super.paintComponent(g);
                g.drawImage(imagenFondo, 0, 0, getWidth(), getHeight(), this);
            }
        };

        getContentPane().setLayout(new AbsoluteLayout());
        getContentPane().add(pnlFondo, new AbsoluteConstraints(0, 0, getWidth(), getHeight()));
        
        this.setLocationRelativeTo(null); 

        pack(); 
    
    }
    
    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnRegistrarAsistencia = new javax.swing.JButton();
        btnVolverMenuPrincipal = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtCodigoAlumno = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1280, 832));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnRegistrarAsistencia.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Utilerias/botones/btnConfirmarAsistencia.png"))); // NOI18N
        btnRegistrarAsistencia.setBorder(null);
        btnRegistrarAsistencia.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        getContentPane().add(btnRegistrarAsistencia, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 610, -1, -1));

        btnVolverMenuPrincipal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Utilerias/botones/btnVolverMenu.png"))); // NOI18N
        btnVolverMenuPrincipal.setBorder(null);
        btnVolverMenuPrincipal.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        getContentPane().add(btnVolverMenuPrincipal, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 610, -1, -1));

        jLabel3.setFont(new java.awt.Font("Menlo", 1, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(30, 47, 86));
        jLabel3.setText("Ingrese el ID del alumno:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 300, 560, 70));

        jLabel4.setFont(new java.awt.Font("Menlo", 1, 55)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(30, 47, 86));
        jLabel4.setText("REGISTRAR ASISTENCIA");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 170, -1, 60));

        txtCodigoAlumno.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        txtCodigoAlumno.setBorder(null);
        getContentPane().add(txtCodigoAlumno, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 410, 580, 50));
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 460, 580, 10));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRegistrarAsistencia;
    private javax.swing.JButton btnVolverMenuPrincipal;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField txtCodigoAlumno;
    // End of variables declaration//GEN-END:variables
}
