
package FRMs.registroAsistencia;

import FRMs.*;
import com.mycompany.presentacion.ControlNavegacion;
import java.awt.Graphics;
import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JPanel;
import org.netbeans.lib.awtextra.AbsoluteConstraints;
import org.netbeans.lib.awtextra.AbsoluteLayout;

/**
 *
 * @author Usuario
 */
public class FrmSeleccionarOpcion extends javax.swing.JFrame {
    private Image imagenFondo;
    private ControlNavegacion controlNav;

    /**
     * Creates new form FrmMenuPrincipal
     */
    public FrmSeleccionarOpcion() {
        initComponents();
        this.setTitle("Registro de asistencia");
        
        this.imagenFondo = new ImageIcon(getClass().getResource("/Utilerias/FondoCERO.jpeg")).getImage();

        JPanel pnlFondo = new javax.swing.JPanel() {
            @Override
            protected void paintComponent(Graphics g) {
                super.paintComponent(g);
                g.drawImage(imagenFondo, 0, 0, getWidth(), getHeight(), this);
            }
        };

        getContentPane().setLayout(new AbsoluteLayout());
        getContentPane().add(pnlFondo, new AbsoluteConstraints(0, 0, getWidth(), getHeight()));
        
        this.setLocationRelativeTo(null); 

        pack(); 
    
    }
    
    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnAsistenciaIndividual = new javax.swing.JButton();
        btnVisualizarAsistencias = new javax.swing.JButton();
        btnGenerarReportes = new javax.swing.JButton();
        btnVolverMenuPrincipal = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1280, 832));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnAsistenciaIndividual.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Utilerias/botones/btnAsistenciaIndividual.png"))); // NOI18N
        btnAsistenciaIndividual.setBorder(null);
        btnAsistenciaIndividual.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        getContentPane().add(btnAsistenciaIndividual, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 300, -1, -1));

        btnVisualizarAsistencias.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Utilerias/botones/btnAsistencias.png"))); // NOI18N
        btnVisualizarAsistencias.setBorder(null);
        btnVisualizarAsistencias.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnVisualizarAsistencias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVisualizarAsistenciasActionPerformed(evt);
            }
        });
        getContentPane().add(btnVisualizarAsistencias, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 380, -1, -1));

        btnGenerarReportes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Utilerias/botones/btnReportes.png"))); // NOI18N
        btnGenerarReportes.setBorder(null);
        btnGenerarReportes.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        getContentPane().add(btnGenerarReportes, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 460, -1, -1));

        btnVolverMenuPrincipal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Utilerias/botones/btnVolverMenu.png"))); // NOI18N
        btnVolverMenuPrincipal.setBorder(null);
        btnVolverMenuPrincipal.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        getContentPane().add(btnVolverMenuPrincipal, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 560, -1, -1));

        jLabel3.setFont(new java.awt.Font("Menlo", 1, 55)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(30, 47, 86));
        jLabel3.setText("CONTROL DE ASISTENCIAS");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 170, -1, 60));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnVisualizarAsistenciasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVisualizarAsistenciasActionPerformed

    }//GEN-LAST:event_btnVisualizarAsistenciasActionPerformed

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAsistenciaIndividual;
    private javax.swing.JButton btnGenerarReportes;
    private javax.swing.JButton btnVisualizarAsistencias;
    private javax.swing.JButton btnVolverMenuPrincipal;
    private javax.swing.JLabel jLabel3;
    // End of variables declaration//GEN-END:variables
}
