package FRMs.GestionarClases;

import DTOs.GestionarClases.AlumnoClaseDTO;
import DTOs.GestionarClases.ClaseListaDTO;
import FRM.GestionarAlumnos.*;
import com.mycompany.dtos.AlumnoDTO;
import com.mycompany.dtos.InscripcionClaseDTO;
import com.mycompany.presentacion.ControlNavegacion;
import java.awt.BorderLayout;
import java.awt.Graphics;
import java.awt.Image;
import java.util.List;
import javax.swing.BorderFactory;
import javax.swing.BoxLayout;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JPanel;
import javax.swing.JScrollPane;

/**
 *
 * @author Jack Murrieta
 */
public class FrmAlumnosClase extends javax.swing.JFrame {

    private Image imagenFondo;
    private List<AlumnoClaseDTO> inscripciones;
    private ClaseListaDTO claseLista;

    /**
     * Creates new form FrmClasesExistentes
     *
     * @param inscripciones 
     */
    public FrmAlumnosClase(ClaseListaDTO claseLista, List<AlumnoClaseDTO> inscripciones) {
        this.inscripciones = inscripciones;
        this.claseLista = claseLista;
  
        initComponents();

        // Cargar la imagen de fondo
        this.imagenFondo = new ImageIcon(getClass().getResource("/Utilerias/FondoCERO.jpeg")).getImage();

        // Sobrescribir el paintComponent del panelFondo ya creado en initComponents
        panelFondo = new JPanel(new BorderLayout(10, 0)) {
            @Override
            protected void paintComponent(Graphics g) {
                super.paintComponent(g);
                g.drawImage(imagenFondo, 0, 0, getWidth(), getHeight(), this);
            }
        };

        // Reaplicar los paneles a panelFondo con transparencia
        panelFondo.add(Header, BorderLayout.PAGE_START);
        panelFondo.add(panelScroll, BorderLayout.CENTER);
        panelFondo.add(panelBotones, BorderLayout.PAGE_END);

        // Hacer todos los paneles hijos transparentes
        hacerPanelesTransparentes();

        // Usar panelFondo como contenido principal del JFrame
        setContentPane(panelFondo);

        // Configuración del frame
        setTitle("Administración alumnos");
        setSize(1300, 500);
        setLocationRelativeTo(null);
        setVisible(true);
 
        String capacidad = String.valueOf(claseLista.getCapacidad());
        String cuposDisponibles = String.valueOf(claseLista.getCupo());
        String totalInscripciones = String.valueOf(inscripciones.size());

        lblCapacidadGrupo.setText(capacidad);
        lblTotalInscripciones.setText(totalInscripciones);
        lblCuposDisponibles.setText(cuposDisponibles);
        
        llenarInscripcionesAlumno(inscripciones);
    }

    private void hacerPanelesTransparentes() {
        Header.setOpaque(false);
        panelFiltros.setOpaque(false);
        panelBusqueda.setOpaque(false);
        panelTipoFiltro.setOpaque(false);
        panelBotones.setOpaque(false);
        panelBtnAñadir.setOpaque(false);
        panelScroll.setOpaque(false);
        jScrollClases.setOpaque(false);
        jScrollClases.getViewport().setOpaque(false);
    }

    private void llenarInscripcionesAlumno(List<AlumnoClaseDTO> inscripciones) {
        // Crear un JPanel contenedor para la tabla
        JPanel contenedorTabla = new JPanel();
        contenedorTabla.setLayout(new BoxLayout(contenedorTabla, BoxLayout.Y_AXIS));
        contenedorTabla.setOpaque(false); // Que el contenedor también sea transparente
        // Agregar margen para que los elementos no se vean pegados
        contenedorTabla.setBorder(BorderFactory.createEmptyBorder(10, 10, 10, 10));
        // Recorrer la lista de clases y agregar filas a la tabla
        for (AlumnoClaseDTO inscripcion : inscripciones) {
            // Crear el panel para la clase
            JpanelNumeroListaAlumno panelInscripcion = new JpanelNumeroListaAlumno(inscripcion);

            // Agregar espacio entre los paneles
            panelInscripcion.setBorder(BorderFactory.createEmptyBorder(5, 5, 5, 5));

            // Agregar el panel al contenedor
            contenedorTabla.add(panelInscripcion);
        }

        // Configurar JScrollPane
        jScrollClases.setViewportView(contenedorTabla);
        jScrollClases.setVerticalScrollBarPolicy(JScrollPane.VERTICAL_SCROLLBAR_ALWAYS);
        jScrollClases.setHorizontalScrollBarPolicy(JScrollPane.HORIZONTAL_SCROLLBAR_NEVER);

        // Asegurar que la tabla se muestre correctamente
        contenedorTabla.revalidate();
        contenedorTabla.repaint();
    }


    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelFondo = new javax.swing.JPanel();
        Header = new javax.swing.JPanel();
        lblTitulo = new javax.swing.JLabel();
        panelFiltros = new javax.swing.JPanel();
        panelBusqueda = new javax.swing.JPanel();
        campoVacio = new javax.swing.JLabel();
        lblColumnCapGrupo = new javax.swing.JLabel();
        lblTotalInscrp = new javax.swing.JLabel();
        lblCuposDisp = new javax.swing.JLabel();
        lblNombreClase2 = new javax.swing.JLabel();
        panelTipoFiltro = new javax.swing.JPanel();
        campoVacio2 = new javax.swing.JLabel();
        lblCapacidadGrupo = new javax.swing.JLabel();
        lblTotalInscripciones = new javax.swing.JLabel();
        lblCuposDisponibles = new javax.swing.JLabel();
        campoVacio6 = new javax.swing.JLabel();
        panelBotones = new javax.swing.JPanel();
        panelBtnAñadir = new javax.swing.JPanel();
        btnRegresar = new javax.swing.JButton();
        panelScroll = new javax.swing.JPanel();
        jScrollClases = new javax.swing.JScrollPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panelFondo.setLayout(new java.awt.BorderLayout(10, 0));

        Header.setLayout(new java.awt.BorderLayout(10, 40));

        lblTitulo.setFont(new java.awt.Font("Menlo", 1, 48));
        lblTitulo.setForeground(new java.awt.Color(30, 47, 86));
        lblTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitulo.setText("ALUMNOS INSCRITOS");
        Header.add(lblTitulo, java.awt.BorderLayout.PAGE_START);

        panelFiltros.setLayout(new java.awt.GridLayout(2, 1, 10, 25));

        panelBusqueda.setLayout(new java.awt.GridLayout(1, 3, 40, 0));

        campoVacio.setFont(new java.awt.Font("Menlo", 1, 24)); // NOI18N
        campoVacio.setForeground(new java.awt.Color(30, 47, 86));
        campoVacio.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        panelBusqueda.add(campoVacio);

        lblColumnCapGrupo.setBackground(new java.awt.Color(255, 255, 255));
        lblColumnCapGrupo.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblColumnCapGrupo.setForeground(new java.awt.Color(255, 255, 255));
        lblColumnCapGrupo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblColumnCapGrupo.setText("CAPACIDAD DEL GRUPO");
        lblColumnCapGrupo.setOpaque(false);
        panelBusqueda.add(lblColumnCapGrupo);

        lblTotalInscrp.setBackground(new java.awt.Color(255, 255, 255));
        lblTotalInscrp.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblTotalInscrp.setForeground(new java.awt.Color(255, 255, 255));
        lblTotalInscrp.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTotalInscrp.setText("TOTAL INSCRIPCIONES");
        lblTotalInscrp.setOpaque(false);
        panelBusqueda.add(lblTotalInscrp);

        lblCuposDisp.setBackground(new java.awt.Color(255, 255, 255));
        lblCuposDisp.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblCuposDisp.setForeground(new java.awt.Color(255, 255, 255));
        lblCuposDisp.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblCuposDisp.setText("CUPOS DISPONIBLES");
        lblCuposDisp.setOpaque(false);
        panelBusqueda.add(lblCuposDisp);

        lblNombreClase2.setFont(new java.awt.Font("Menlo", 1, 24)); // NOI18N
        lblNombreClase2.setForeground(new java.awt.Color(30, 47, 86));
        lblNombreClase2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        panelBusqueda.add(lblNombreClase2);

        panelFiltros.add(panelBusqueda);

        panelTipoFiltro.setLayout(new java.awt.GridLayout(1, 3, 40, 5));

        campoVacio2.setFont(new java.awt.Font("Menlo", 1, 24)); // NOI18N
        campoVacio2.setForeground(new java.awt.Color(30, 47, 86));
        campoVacio2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        panelTipoFiltro.add(campoVacio2);

        lblCapacidadGrupo.setBackground(new java.awt.Color(255, 255, 255));
        lblCapacidadGrupo.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblCapacidadGrupo.setForeground(new java.awt.Color(255, 255, 255));
        lblCapacidadGrupo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblCapacidadGrupo.setText("0");
        lblCapacidadGrupo.setOpaque(false);
        panelTipoFiltro.add(lblCapacidadGrupo);

        lblTotalInscripciones.setBackground(new java.awt.Color(255, 255, 255));
        lblTotalInscripciones.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblTotalInscripciones.setForeground(new java.awt.Color(255, 255, 255));
        lblTotalInscripciones.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTotalInscripciones.setText("5");
        lblTotalInscripciones.setOpaque(false);
        panelTipoFiltro.add(lblTotalInscripciones);

        lblCuposDisponibles.setBackground(new java.awt.Color(255, 255, 255));
        lblCuposDisponibles.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblCuposDisponibles.setForeground(new java.awt.Color(255, 255, 255));
        lblCuposDisponibles.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblCuposDisponibles.setText("8");
        lblCuposDisponibles.setOpaque(false);
        panelTipoFiltro.add(lblCuposDisponibles);

        campoVacio6.setFont(new java.awt.Font("Menlo", 1, 24)); // NOI18N
        campoVacio6.setForeground(new java.awt.Color(30, 47, 86));
        campoVacio6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        panelTipoFiltro.add(campoVacio6);

        panelFiltros.add(panelTipoFiltro);

        Header.add(panelFiltros, java.awt.BorderLayout.CENTER);

        panelFondo.add(Header, java.awt.BorderLayout.PAGE_START);

        panelBotones.setLayout(new java.awt.BorderLayout());

        javax.swing.GroupLayout panelBtnAñadirLayout = new javax.swing.GroupLayout(panelBtnAñadir);
        panelBtnAñadir.setLayout(panelBtnAñadirLayout);
        panelBtnAñadirLayout.setHorizontalGroup(
            panelBtnAñadirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 293, Short.MAX_VALUE)
        );
        panelBtnAñadirLayout.setVerticalGroup(
            panelBtnAñadirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        panelBotones.add(panelBtnAñadir, java.awt.BorderLayout.LINE_END);

        btnRegresar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Utilerias/botones/btnRegresarGrande.png"))); // NOI18N
        btnRegresar.setBorderPainted(false);
        btnRegresar.setContentAreaFilled(false);
        btnRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegresarActionPerformed(evt);
            }
        });
        panelBotones.add(btnRegresar, java.awt.BorderLayout.CENTER);

        panelFondo.add(panelBotones, java.awt.BorderLayout.PAGE_END);

        panelScroll.setLayout(new java.awt.BorderLayout());

        jScrollClases.setBorder(null);
        panelScroll.add(jScrollClases, java.awt.BorderLayout.CENTER);

        panelFondo.add(panelScroll, java.awt.BorderLayout.CENTER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelFondo, javax.swing.GroupLayout.DEFAULT_SIZE, 1377, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panelFondo, javax.swing.GroupLayout.PREFERRED_SIZE, 695, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresarActionPerformed
        // TODO add your handling code here:
        this.dispose();
        ControlNavegacion.mostrarFrmAdminClases();

    }//GEN-LAST:event_btnRegresarActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Header;
    private javax.swing.JButton btnRegresar;
    private javax.swing.JLabel campoVacio;
    private javax.swing.JLabel campoVacio2;
    private javax.swing.JLabel campoVacio6;
    private javax.swing.JScrollPane jScrollClases;
    private javax.swing.JLabel lblCapacidadGrupo;
    private javax.swing.JLabel lblColumnCapGrupo;
    private javax.swing.JLabel lblCuposDisp;
    private javax.swing.JLabel lblCuposDisponibles;
    private javax.swing.JLabel lblNombreClase2;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JLabel lblTotalInscripciones;
    private javax.swing.JLabel lblTotalInscrp;
    private javax.swing.JPanel panelBotones;
    private javax.swing.JPanel panelBtnAñadir;
    private javax.swing.JPanel panelBusqueda;
    private javax.swing.JPanel panelFiltros;
    private javax.swing.JPanel panelFondo;
    private javax.swing.JPanel panelScroll;
    private javax.swing.JPanel panelTipoFiltro;
    // End of variables declaration//GEN-END:variables
}
