package FRMs.GestionarClases;

import DTOs.GestionarClases.ClaseListaDTO;
import java.awt.BorderLayout;
import java.awt.Graphics;
import java.awt.Image;
import java.util.ArrayList;
import java.util.List;
import javax.swing.BorderFactory;
import javax.swing.BoxLayout;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JPanel;
import javax.swing.JScrollPane;

/**
 *
 * @author Jack Murrieta
 */
public class FrmAdminClases extends javax.swing.JFrame {

    private Image imagenFondo;
    private List<ClaseListaDTO> clases;

    /**
     * Creates new form FrmClasesExistentes
     *
     * @param clases
     */
    public FrmAdminClases(List<ClaseListaDTO> clases) {
        this.clases = clases;
        initComponents();

        // Cargar la imagen de fondo
        this.imagenFondo = new ImageIcon(getClass().getResource("/Utilerias/FondoCERO.jpeg")).getImage();

        // Sobrescribir el paintComponent del panelFondo ya creado en initComponents
        panelFondo = new JPanel(new BorderLayout(10, 0)) {
            @Override
            protected void paintComponent(Graphics g) {
                super.paintComponent(g);
                g.drawImage(imagenFondo, 0, 0, getWidth(), getHeight(), this);
            }
        };

        // Reaplicar los paneles a panelFondo con transparencia
        panelFondo.add(Header, BorderLayout.PAGE_START);
        panelFondo.add(panelScroll, BorderLayout.CENTER);
        panelFondo.add(panelBotones, BorderLayout.PAGE_END);

        // Hacer todos los paneles hijos transparentes
        hacerPanelesTransparentes();

        // Usar panelFondo como contenido principal del JFrame
        setContentPane(panelFondo);

        // Configuración del frame
        setTitle("Administración Clases");
        setSize(1300, 500);
        setLocationRelativeTo(null);
        setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        setVisible(true);

        llenarClasesExistentes(clases);
    }

    private void hacerPanelesTransparentes() {
        Header.setOpaque(false);
        panelFiltros.setOpaque(false);
        panelBusqueda.setOpaque(false);
        panelTipoFiltro.setOpaque(false);
        panelBotones.setOpaque(false);
        panelBtnAñadir.setOpaque(false);
        panelBtnRegresar.setOpaque(false);
        panelScroll.setOpaque(false);
        jScrollClases.setOpaque(false);
        jScrollClases.getViewport().setOpaque(false);
    }

    private void llenarClasesExistentes(List<ClaseListaDTO> clases) {
        // Crear un JPanel contenedor para la tabla
        JPanel contenedorTabla = new JPanel();
        contenedorTabla.setLayout(new BoxLayout(contenedorTabla, BoxLayout.Y_AXIS));
        contenedorTabla.setOpaque(false); // Que el contenedor también sea transparente
        // Agregar margen para que los elementos no se vean pegados
        contenedorTabla.setBorder(BorderFactory.createEmptyBorder(10, 10, 10, 10));
        // Recorrer la lista de clases y agregar filas a la tabla
        for (ClaseListaDTO clase : clases) {
            // Crear el panel para la clase
            JpanelClaseListaAdmin panelClase = new JpanelClaseListaAdmin(clase);

            // Agregar espacio entre los paneles
            panelClase.setBorder(BorderFactory.createEmptyBorder(5, 5, 5, 5));

            // Agregar el panel al contenedor
            contenedorTabla.add(panelClase);
        }

        // Configurar JScrollPane
        jScrollClases.setViewportView(contenedorTabla);
        jScrollClases.setVerticalScrollBarPolicy(JScrollPane.VERTICAL_SCROLLBAR_ALWAYS);
        jScrollClases.setHorizontalScrollBarPolicy(JScrollPane.HORIZONTAL_SCROLLBAR_NEVER);

        // Asegurar que la tabla se muestre correctamente
        contenedorTabla.revalidate();
        contenedorTabla.repaint();
    }

    private List<ClaseListaDTO> filtroListas(boolean activo) {
        List<ClaseListaDTO> clasesFiltro = new ArrayList<>();
        for (ClaseListaDTO clase : clases) {
            if (clase.isActiva() == activo) {
                clasesFiltro.add(clase);
            }

        }
        return clasesFiltro;

    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelFondo = new javax.swing.JPanel();
        Header = new javax.swing.JPanel();
        lblTitulo = new javax.swing.JLabel();
        panelFiltros = new javax.swing.JPanel();
        panelBusqueda = new javax.swing.JPanel();
        campoVacio = new javax.swing.JLabel();
        cmpoVacio1 = new javax.swing.JLabel();
        txtBuscar = new javax.swing.JTextField();
        btnBuscar = new javax.swing.JButton();
        lblNombreClase2 = new javax.swing.JLabel();
        panelTipoFiltro = new javax.swing.JPanel();
        campoVacio2 = new javax.swing.JLabel();
        lblFiltrar = new javax.swing.JLabel();
        btnActivas = new javax.swing.JButton();
        btnInactivas = new javax.swing.JButton();
        btnNinguno = new javax.swing.JButton();
        campoVacio3 = new javax.swing.JLabel();
        panelBotones = new javax.swing.JPanel();
        panelBtnRegresar = new javax.swing.JPanel();
        jButton5 = new javax.swing.JButton();
        panelBtnAñadir = new javax.swing.JPanel();
        btnNuevaClase = new javax.swing.JButton();
        panelScroll = new javax.swing.JPanel();
        jScrollClases = new javax.swing.JScrollPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panelFondo.setLayout(new java.awt.BorderLayout(10, 0));

        Header.setLayout(new java.awt.BorderLayout(10, 40));

        lblTitulo.setFont(new java.awt.Font("Menlo", 1, 48));
        lblTitulo.setForeground(new java.awt.Color(30, 47, 86));
        lblTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitulo.setText("ADMINISTRACION CLASES");
        Header.add(lblTitulo, java.awt.BorderLayout.PAGE_START);

        panelFiltros.setLayout(new java.awt.GridLayout(2, 1, 10, 25));

        panelBusqueda.setLayout(new java.awt.GridLayout(1, 3, 40, 0));

        campoVacio.setFont(new java.awt.Font("Menlo", 1, 24)); // NOI18N
        campoVacio.setForeground(new java.awt.Color(30, 47, 86));
        campoVacio.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        panelBusqueda.add(campoVacio);

        cmpoVacio1.setFont(new java.awt.Font("Menlo", 1, 24)); // NOI18N
        cmpoVacio1.setForeground(new java.awt.Color(30, 47, 86));
        cmpoVacio1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        cmpoVacio1.setText("Nombre de la clase:");
        panelBusqueda.add(cmpoVacio1);

        txtBuscar.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        panelBusqueda.add(txtBuscar);

        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });
        panelBusqueda.add(btnBuscar);

        lblNombreClase2.setFont(new java.awt.Font("Menlo", 1, 24)); // NOI18N
        lblNombreClase2.setForeground(new java.awt.Color(30, 47, 86));
        lblNombreClase2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        panelBusqueda.add(lblNombreClase2);

        panelFiltros.add(panelBusqueda);

        panelTipoFiltro.setLayout(new java.awt.GridLayout(1, 3, 40, 5));

        campoVacio2.setFont(new java.awt.Font("Menlo", 1, 24)); // NOI18N
        campoVacio2.setForeground(new java.awt.Color(30, 47, 86));
        campoVacio2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        panelTipoFiltro.add(campoVacio2);

        lblFiltrar.setFont(new java.awt.Font("Menlo", 1, 24)); // NOI18N
        lblFiltrar.setForeground(new java.awt.Color(30, 47, 86));
        lblFiltrar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblFiltrar.setText("Filtrar:");
        panelTipoFiltro.add(lblFiltrar);

        btnActivas.setBackground(new java.awt.Color(255, 255, 255));
        btnActivas.setForeground(new java.awt.Color(0, 157, 255));
        btnActivas.setText("Activas");
        btnActivas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActivasActionPerformed(evt);
            }
        });
        panelTipoFiltro.add(btnActivas);

        btnInactivas.setBackground(new java.awt.Color(255, 255, 255));
        btnInactivas.setForeground(new java.awt.Color(0, 157, 255));
        btnInactivas.setText("Inactivas");
        btnInactivas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInactivasActionPerformed(evt);
            }
        });
        panelTipoFiltro.add(btnInactivas);

        btnNinguno.setBackground(new java.awt.Color(255, 255, 255));
        btnNinguno.setForeground(new java.awt.Color(0, 157, 255));
        btnNinguno.setText("NONE");
        btnNinguno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNingunoActionPerformed(evt);
            }
        });
        panelTipoFiltro.add(btnNinguno);

        campoVacio3.setFont(new java.awt.Font("Menlo", 1, 24)); // NOI18N
        campoVacio3.setForeground(new java.awt.Color(30, 47, 86));
        campoVacio3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        panelTipoFiltro.add(campoVacio3);

        panelFiltros.add(panelTipoFiltro);

        Header.add(panelFiltros, java.awt.BorderLayout.CENTER);

        panelFondo.add(Header, java.awt.BorderLayout.PAGE_START);

        panelBotones.setLayout(new java.awt.BorderLayout());

        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Utilerias/botones/btnRegresarClase.png"))); // NOI18N
        jButton5.setBorderPainted(false);
        jButton5.setContentAreaFilled(false);
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelBtnRegresarLayout = new javax.swing.GroupLayout(panelBtnRegresar);
        panelBtnRegresar.setLayout(panelBtnRegresarLayout);
        panelBtnRegresarLayout.setHorizontalGroup(
            panelBtnRegresarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBtnRegresarLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jButton5)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelBtnRegresarLayout.setVerticalGroup(
            panelBtnRegresarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelBtnRegresarLayout.createSequentialGroup()
                .addContainerGap(19, Short.MAX_VALUE)
                .addComponent(jButton5)
                .addGap(14, 14, 14))
        );

        panelBotones.add(panelBtnRegresar, java.awt.BorderLayout.LINE_START);

        btnNuevaClase.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Utilerias/botones/btnAñadirClase.png"))); // NOI18N
        btnNuevaClase.setBorderPainted(false);
        btnNuevaClase.setContentAreaFilled(false);

        javax.swing.GroupLayout panelBtnAñadirLayout = new javax.swing.GroupLayout(panelBtnAñadir);
        panelBtnAñadir.setLayout(panelBtnAñadirLayout);
        panelBtnAñadirLayout.setHorizontalGroup(
            panelBtnAñadirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBtnAñadirLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnNuevaClase, javax.swing.GroupLayout.PREFERRED_SIZE, 281, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelBtnAñadirLayout.setVerticalGroup(
            panelBtnAñadirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelBtnAñadirLayout.createSequentialGroup()
                .addContainerGap(19, Short.MAX_VALUE)
                .addComponent(btnNuevaClase, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15))
        );

        panelBotones.add(panelBtnAñadir, java.awt.BorderLayout.LINE_END);

        panelFondo.add(panelBotones, java.awt.BorderLayout.PAGE_END);

        panelScroll.setLayout(new java.awt.BorderLayout());

        jScrollClases.setBorder(null);
        panelScroll.add(jScrollClases, java.awt.BorderLayout.CENTER);

        panelFondo.add(panelScroll, java.awt.BorderLayout.CENTER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelFondo, javax.swing.GroupLayout.DEFAULT_SIZE, 1377, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panelFondo, javax.swing.GroupLayout.PREFERRED_SIZE, 695, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnActivasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActivasActionPerformed
        // TODO add your handling code here:
        btnActivas.setBackground(new java.awt.Color(30, 47, 86));
        btnActivas.setForeground(new java.awt.Color(255, 255, 255));
        //Color blanco
        btnInactivas.setBackground(new java.awt.Color(255, 255, 255));
        btnInactivas.setForeground(new java.awt.Color(0, 157, 255));
        btnNinguno.setBackground(new java.awt.Color(255, 255, 255));
        btnNinguno.setForeground(new java.awt.Color(0, 157, 255));

        //FILTRAR LISTA CON ACTIVAS = True
        List<ClaseListaDTO> activas = filtroListas(true);
        llenarClasesExistentes(activas);


    }//GEN-LAST:event_btnActivasActionPerformed

    private void btnInactivasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInactivasActionPerformed
        // TODO add your handling code here:
        //Color azul
        btnInactivas.setBackground(new java.awt.Color(30, 47, 86));
        btnInactivas.setForeground(new java.awt.Color(255, 255, 255));
        //Color blanco
        btnActivas.setBackground(new java.awt.Color(255, 255, 255));
        btnActivas.setForeground(new java.awt.Color(0, 157, 255));
        btnNinguno.setBackground(new java.awt.Color(255, 255, 255));
        btnNinguno.setForeground(new java.awt.Color(0, 157, 255));

        //FILTRAR LISTA CON INACTIVAS = False
        List<ClaseListaDTO> inactivas = filtroListas(false);
        llenarClasesExistentes(inactivas);
    }//GEN-LAST:event_btnInactivasActionPerformed

    private void btnNingunoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNingunoActionPerformed
        // TODO add your handling code here:
        //Color azul
        btnNinguno.setBackground(new java.awt.Color(30, 47, 86));
        btnNinguno.setForeground(new java.awt.Color(255, 255, 255));
        //Color blanco
        btnActivas.setBackground(new java.awt.Color(255, 255, 255));
        btnActivas.setForeground(new java.awt.Color(0, 157, 255));
        btnInactivas.setBackground(new java.awt.Color(255, 255, 255));
        btnInactivas.setForeground(new java.awt.Color(0, 157, 255));
        //MOSTRAR LA MISMA LISTA
        llenarClasesExistentes(clases);
    }//GEN-LAST:event_btnNingunoActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton5ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Header;
    private javax.swing.JButton btnActivas;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnInactivas;
    private javax.swing.JButton btnNinguno;
    private javax.swing.JButton btnNuevaClase;
    private javax.swing.JLabel campoVacio;
    private javax.swing.JLabel campoVacio2;
    private javax.swing.JLabel campoVacio3;
    private javax.swing.JLabel cmpoVacio1;
    private javax.swing.JButton jButton5;
    private javax.swing.JScrollPane jScrollClases;
    private javax.swing.JLabel lblFiltrar;
    private javax.swing.JLabel lblNombreClase2;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JPanel panelBotones;
    private javax.swing.JPanel panelBtnAñadir;
    private javax.swing.JPanel panelBtnRegresar;
    private javax.swing.JPanel panelBusqueda;
    private javax.swing.JPanel panelFiltros;
    private javax.swing.JPanel panelFondo;
    private javax.swing.JPanel panelScroll;
    private javax.swing.JPanel panelTipoFiltro;
    private javax.swing.JTextField txtBuscar;
    // End of variables declaration//GEN-END:variables
}
