/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package FRMs.GestionarClases;

import DTOs.GestionarClases.AulaClaseDTO;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Graphics;
import java.awt.Image;
import java.time.DayOfWeek;
import java.time.LocalDate;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import javax.swing.ImageIcon;
import javax.swing.JCheckBox;
import DTOs.GestionarClases.MaestroDTO;
import DTOs.GestionarClases.NuevaClaseDTO;
import java.time.ZoneId;
import java.util.Date;
import FRMs.GestionarClases.CustomHoraMinutoSpinner.Tipo;
import java.time.LocalTime;

/**
 *
 * @author Jack Murrieta
 */
public class PanelGuardarClase extends javax.swing.JPanel {
    
    private Image imagenFondo;
    private List<DayOfWeek> diasSeleccionados;
    private List<JCheckBox> dias;
    private Map<JCheckBox, DayOfWeek> mapaDias;
    private List<MaestroDTO> maestros;
    private List<AulaClaseDTO> aulas;
    private LocalDate fechaInicio;
    private LocalDate fechaFin;
    /**
     * Creates new form AdminClases
     * @param maestros
     * @param aulas
     */
    public PanelGuardarClase(List<MaestroDTO> maestros , List<AulaClaseDTO> aulas ) {
        // Carga la imagen de fondo
        this.imagenFondo = new ImageIcon(getClass().getResource("/Utilerias/FondoCERO.jpeg")).getImage();
        initComponents();
        setOpaque(false); // Asegura que el fondo se pinte correctamente
        setPreferredSize(new Dimension(1230, 1300));
        dias = new ArrayList<>();
        dias.add(checkBoxLun);
        dias.add(checkBoxMar);
        dias.add(checkBoxMie);
        dias.add(checkBoxJue);
        dias.add(checkBoxVie);
        dias.add(checkBoxSab);
        dias.add(checkBoxDom);
        // Mapeo de cada checkbox a su día correspondiente
        this.mapaDias = new HashMap<>();
        mapaDias.put(checkBoxLun, DayOfWeek.MONDAY);
        mapaDias.put(checkBoxMar, DayOfWeek.TUESDAY);
        mapaDias.put(checkBoxMie, DayOfWeek.WEDNESDAY);
        mapaDias.put(checkBoxJue, DayOfWeek.THURSDAY);
        mapaDias.put(checkBoxVie, DayOfWeek.FRIDAY);
        mapaDias.put(checkBoxSab, DayOfWeek.SATURDAY);
        mapaDias.put(checkBoxDom, DayOfWeek.SUNDAY);
        
        //Configurar la lista con el chechBox
        configurarComboxAulas(aulas);
        configurarComboxMaestro(maestros);
        configurarComboxModalidades();
        
    }
    
    private void configurarComboxMaestro(List<MaestroDTO> maestros) {
        comboxMaestro.removeAllItems();
        for (MaestroDTO maestro : maestros) {
            comboxMaestro.addItem(maestro); // Agrega el objeto, no solo el nombre
        }
    }
    
    private void configurarComboxAulas(List<AulaClaseDTO> aulas) {
        comboxAulas.removeAllItems();
        for (AulaClaseDTO aula : aulas) {
            comboxAulas.addItem(aula); // Igual aquí
        }
    }
    
    private void configurarComboxModalidades() {
        comboxModalidad.removeAllItems();
        comboxModalidad.addItem("Presencial");
        comboxModalidad.addItem("Virtual");
    }
    
    @Override
    protected void paintComponent(Graphics g) {
        super.paintComponent(g);
        // Dibuja la imagen de fondo
        g.drawImage(imagenFondo, 0, 0, getWidth(), getHeight(), this);
    }
    

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelDatosMaestro = new javax.swing.JPanel();
        lblIP3 = new javax.swing.JLabel();
        comboxMaestro = new javax.swing.JComboBox<>();
        lblIP1 = new javax.swing.JLabel();
        panelDatosClase = new javax.swing.JPanel();
        lblIP2 = new javax.swing.JLabel();
        txtNomClase = new javax.swing.JTextField();
        lblIP4 = new javax.swing.JLabel();
        lblIP5 = new javax.swing.JLabel();
        diasClasesPanel = new javax.swing.JPanel();
        lblIP7 = new javax.swing.JLabel();
        lblIP8 = new javax.swing.JLabel();
        lblIP9 = new javax.swing.JLabel();
        lblIP10 = new javax.swing.JLabel();
        lblIP6 = new javax.swing.JLabel();
        lblIP11 = new javax.swing.JLabel();
        lblIP12 = new javax.swing.JLabel();
        ComboxPanel = new javax.swing.JPanel();
        checkBoxLun = new javax.swing.JCheckBox();
        checkBoxMar = new javax.swing.JCheckBox();
        checkBoxMie = new javax.swing.JCheckBox();
        checkBoxJue = new javax.swing.JCheckBox();
        checkBoxVie = new javax.swing.JCheckBox();
        checkBoxSab = new javax.swing.JCheckBox();
        checkBoxDom = new javax.swing.JCheckBox();
        panelModalidad = new javax.swing.JPanel();
        lblIP = new javax.swing.JLabel();
        comboxModalidad = new javax.swing.JComboBox<>();
        jCalendarFechaInicio = new com.toedter.calendar.JCalendar();
        lblIP13 = new javax.swing.JLabel();
        jCalendarFechaFin = new com.toedter.calendar.JCalendar();
        lblIP15 = new javax.swing.JLabel();
        lblIP16 = new javax.swing.JLabel();
        panelHoraInicio = new javax.swing.JPanel();
        spinnerHoraInicio = new FRMs.GestionarClases.CustomHoraMinutoSpinner(Tipo.HORA)
        ;
        lblHora = new javax.swing.JLabel();
        spinnerMinutosInicio = new FRMs.GestionarClases.CustomHoraMinutoSpinner(FRMs.GestionarClases.CustomHoraMinutoSpinner.Tipo.MINUTO);
        panelHoraFin = new javax.swing.JPanel();
        spinnerHoraFin = new FRMs.GestionarClases.CustomHoraMinutoSpinner(Tipo.HORA);
        lblHora1 = new javax.swing.JLabel();
        spinnerMinutosFin = new FRMs.GestionarClases.CustomHoraMinutoSpinner(Tipo.MINUTO);
        lblIP17 = new javax.swing.JLabel();
        lblIP18 = new javax.swing.JLabel();
        panelCantidadPrecio = new javax.swing.JPanel();
        lblIP14 = new javax.swing.JLabel();
        capacidad = new CustomCapacidadSpinner();
        lblIP19 = new javax.swing.JLabel();
        spinnerPrecio = new CustomPrecioSpinner();
        btnGuardar = new javax.swing.JButton();
        btnRegresar2 = new javax.swing.JButton();
        panelAula = new javax.swing.JPanel();
        lblIP20 = new javax.swing.JLabel();
        comboxAulas = new javax.swing.JComboBox<>();

        setLayout(null);

        panelDatosMaestro.setBackground(new Color(0, 0, 0, 0));
        panelDatosMaestro.setOpaque(false);
        panelDatosMaestro.setLayout(new java.awt.GridLayout(2, 1));

        lblIP3.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lblIP3.setForeground(new java.awt.Color(255, 255, 255));
        lblIP3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblIP3.setText("Maestro:");
        panelDatosMaestro.add(lblIP3);

        comboxMaestro.setFont(new java.awt.Font("Dialog", 1, 18));
        comboxMaestro.setForeground(new java.awt.Color(30, 47, 86));
        comboxMaestro.setModel(new javax.swing.DefaultComboBoxModel<>());
        comboxMaestro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboxMaestroActionPerformed(evt);
            }
        });
        panelDatosMaestro.add(comboxMaestro);

        add(panelDatosMaestro);
        panelDatosMaestro.setBounds(420, 140, 270, 80);

        lblIP1.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        lblIP1.setForeground(new java.awt.Color(30, 47, 86));
        lblIP1.setText("Capacidad y Precio:");
        add(lblIP1);
        lblIP1.setBounds(40, 930, 230, 32);

        panelDatosClase.setBackground(new Color(0, 0, 0, 0));
        panelDatosClase.setOpaque(false);
        panelDatosClase.setLayout(new java.awt.GridLayout(2, 1, 3, 0));

        lblIP2.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lblIP2.setForeground(new java.awt.Color(255, 255, 255));
        lblIP2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblIP2.setText("Nombre Clase:");
        panelDatosClase.add(lblIP2);

        txtNomClase.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        txtNomClase.setForeground(new java.awt.Color(30, 47, 86));
        txtNomClase.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtNomClase.setText("ingresa nombre clase...");
        txtNomClase.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtNomClaseMouseClicked(evt);
            }
        });
        panelDatosClase.add(txtNomClase);

        add(panelDatosClase);
        panelDatosClase.setBounds(80, 140, 290, 80);

        lblIP4.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        lblIP4.setForeground(new java.awt.Color(30, 47, 86));
        lblIP4.setText("Informacion General:");
        add(lblIP4);
        lblIP4.setBounds(40, 80, 280, 46);

        lblIP5.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lblIP5.setForeground(new java.awt.Color(255, 255, 255));
        lblIP5.setText("Hora Fin:");
        add(lblIP5);
        lblIP5.setBounds(560, 670, 150, 30);

        diasClasesPanel.setBackground(new Color(0, 0, 0, 0));
        diasClasesPanel.setOpaque(false);
        diasClasesPanel.setLayout(new java.awt.GridLayout(1, 7, 5, 5));

        lblIP7.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lblIP7.setForeground(new java.awt.Color(255, 255, 255));
        lblIP7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblIP7.setText("LUN");
        diasClasesPanel.add(lblIP7);

        lblIP8.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lblIP8.setForeground(new java.awt.Color(255, 255, 255));
        lblIP8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblIP8.setText("MAR");
        diasClasesPanel.add(lblIP8);

        lblIP9.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lblIP9.setForeground(new java.awt.Color(255, 255, 255));
        lblIP9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblIP9.setText("MIE");
        diasClasesPanel.add(lblIP9);

        lblIP10.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lblIP10.setForeground(new java.awt.Color(255, 255, 255));
        lblIP10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblIP10.setText("JUE");
        diasClasesPanel.add(lblIP10);

        lblIP6.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lblIP6.setForeground(new java.awt.Color(255, 255, 255));
        lblIP6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblIP6.setText("VIE");
        diasClasesPanel.add(lblIP6);

        lblIP11.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lblIP11.setForeground(new java.awt.Color(255, 255, 255));
        lblIP11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblIP11.setText("SAB");
        diasClasesPanel.add(lblIP11);

        lblIP12.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lblIP12.setForeground(new java.awt.Color(255, 255, 255));
        lblIP12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblIP12.setText("DOM");
        diasClasesPanel.add(lblIP12);

        add(diasClasesPanel);
        diasClasesPanel.setBounds(190, 300, 470, 30);

        ComboxPanel.setBackground(new Color(0, 0, 0, 0));
        ComboxPanel.setOpaque(false);
        ComboxPanel.setLayout(new java.awt.GridLayout(1, 7));

        checkBoxLun.setBackground(new Color(0, 0, 0, 0));
        checkBoxLun.setFont(new java.awt.Font("Dialog", 0, 48)); // NOI18N
        checkBoxLun.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        checkBoxLun.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        checkBoxLun.setName(""); // NOI18N
        checkBoxLun.setOpaque(false);
        checkBoxLun.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        checkBoxLun.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        checkBoxLun.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkBoxLunActionPerformed(evt);
            }
        });
        ComboxPanel.add(checkBoxLun);

        checkBoxMar.setBackground(new Color(0, 0, 0, 0));
        checkBoxMar.setFont(new java.awt.Font("Dialog", 0, 48)); // NOI18N
        checkBoxMar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        checkBoxMar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        checkBoxMar.setName(""); // NOI18N
        checkBoxMar.setOpaque(false);
        checkBoxMar.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        checkBoxMar.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        checkBoxMar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkBoxMarActionPerformed(evt);
            }
        });
        ComboxPanel.add(checkBoxMar);

        checkBoxMie.setBackground(new Color(0, 0, 0, 0));
        checkBoxMie.setFont(new java.awt.Font("Dialog", 0, 48)); // NOI18N
        checkBoxMie.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        checkBoxMie.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        checkBoxMie.setName(""); // NOI18N
        checkBoxMie.setOpaque(false);
        checkBoxMie.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        checkBoxMie.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        checkBoxMie.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkBoxMieActionPerformed(evt);
            }
        });
        ComboxPanel.add(checkBoxMie);

        checkBoxJue.setBackground(new Color(0, 0, 0, 0));
        checkBoxJue.setFont(new java.awt.Font("Dialog", 0, 48)); // NOI18N
        checkBoxJue.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        checkBoxJue.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        checkBoxJue.setName(""); // NOI18N
        checkBoxJue.setOpaque(false);
        checkBoxJue.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        checkBoxJue.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        checkBoxJue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkBoxJueActionPerformed(evt);
            }
        });
        ComboxPanel.add(checkBoxJue);

        checkBoxVie.setBackground(new Color(0, 0, 0, 0));
        checkBoxVie.setFont(new java.awt.Font("Dialog", 0, 48)); // NOI18N
        checkBoxVie.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        checkBoxVie.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        checkBoxVie.setName(""); // NOI18N
        checkBoxVie.setOpaque(false);
        checkBoxVie.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        checkBoxVie.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        checkBoxVie.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkBoxVieActionPerformed(evt);
            }
        });
        ComboxPanel.add(checkBoxVie);

        checkBoxSab.setBackground(new Color(0, 0, 0, 0));
        checkBoxSab.setFont(new java.awt.Font("Dialog", 0, 48)); // NOI18N
        checkBoxSab.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        checkBoxSab.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        checkBoxSab.setName(""); // NOI18N
        checkBoxSab.setOpaque(false);
        checkBoxSab.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        checkBoxSab.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        checkBoxSab.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkBoxSabActionPerformed(evt);
            }
        });
        ComboxPanel.add(checkBoxSab);

        checkBoxDom.setBackground(new Color(0, 0, 0, 0));
        checkBoxDom.setFont(new java.awt.Font("Dialog", 0, 48)); // NOI18N
        checkBoxDom.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        checkBoxDom.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        checkBoxDom.setName(""); // NOI18N
        checkBoxDom.setOpaque(false);
        checkBoxDom.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        checkBoxDom.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        checkBoxDom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkBoxDomActionPerformed(evt);
            }
        });
        ComboxPanel.add(checkBoxDom);

        add(ComboxPanel);
        ComboxPanel.setBounds(190, 330, 470, 24);

        panelModalidad.setBackground(new Color(0, 0, 0, 0));
        panelModalidad.setOpaque(false);
        panelModalidad.setLayout(new java.awt.GridLayout(2, 1, 3, 0));

        lblIP.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lblIP.setForeground(new java.awt.Color(255, 255, 255));
        lblIP.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblIP.setText("Modalidad:");
        panelModalidad.add(lblIP);

        comboxModalidad.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        comboxModalidad.setForeground(new java.awt.Color(30, 47, 86));
        comboxModalidad.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        comboxModalidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboxModalidadActionPerformed(evt);
            }
        });
        panelModalidad.add(comboxModalidad);

        add(panelModalidad);
        panelModalidad.setBounds(750, 140, 290, 80);

        jCalendarFechaInicio.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                jCalendarFechaInicioPropertyChange(evt);
            }
        });
        add(jCalendarFechaInicio);
        jCalendarFechaInicio.setBounds(140, 450, 270, 210);

        lblIP13.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lblIP13.setForeground(new java.awt.Color(255, 255, 255));
        lblIP13.setText("Dias de clases:");
        add(lblIP13);
        lblIP13.setBounds(40, 320, 140, 30);

        jCalendarFechaFin.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                jCalendarFechaFinPropertyChange(evt);
            }
        });
        add(jCalendarFechaFin);
        jCalendarFechaFin.setBounds(140, 720, 270, 200);

        lblIP15.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lblIP15.setForeground(new java.awt.Color(255, 255, 255));
        lblIP15.setText("Fecha de inicio:");
        add(lblIP15);
        lblIP15.setBounds(40, 400, 150, 30);

        lblIP16.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lblIP16.setForeground(new java.awt.Color(255, 255, 255));
        lblIP16.setText("Hora inicio:");
        add(lblIP16);
        lblIP16.setBounds(560, 400, 150, 30);

        panelHoraInicio.setBackground(new Color(0, 0, 0, 0));
        panelHoraInicio.setOpaque(false);
        panelHoraInicio.setLayout(new java.awt.GridLayout(1, 2, 0, 30));

        spinnerHoraInicio.setFont(new java.awt.Font("Dialog", 1, 24));
        spinnerHoraInicio.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                spinnerHoraInicioStateChanged(evt);
            }
        });
        panelHoraInicio.add(spinnerHoraInicio);

        lblHora.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        lblHora.setForeground(new java.awt.Color(30, 47, 86));
        lblHora.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblHora.setText(":");
        panelHoraInicio.add(lblHora);

        spinnerMinutosInicio.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        spinnerMinutosInicio.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                spinnerMinutosInicioStateChanged(evt);
            }
        });
        panelHoraInicio.add(spinnerMinutosInicio);

        add(panelHoraInicio);
        panelHoraInicio.setBounds(560, 450, 370, 50);

        panelHoraFin.setBackground(new Color(0, 0, 0, 0));
        panelHoraFin.setOpaque(false);
        panelHoraFin.setLayout(new java.awt.GridLayout(1, 2, 0, 30));

        spinnerHoraFin.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        spinnerHoraFin.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                spinnerHoraFinStateChanged(evt);
            }
        });
        panelHoraFin.add(spinnerHoraFin);

        lblHora1.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        lblHora1.setForeground(new java.awt.Color(30, 47, 86));
        lblHora1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblHora1.setText(":");
        panelHoraFin.add(lblHora1);

        spinnerMinutosFin.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        spinnerMinutosFin.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                spinnerMinutosFinStateChanged(evt);
            }
        });
        panelHoraFin.add(spinnerMinutosFin);

        add(panelHoraFin);
        panelHoraFin.setBounds(560, 730, 380, 50);

        lblIP17.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        lblIP17.setForeground(new java.awt.Color(30, 47, 86));
        lblIP17.setText("Horario:");
        add(lblIP17);
        lblIP17.setBounds(40, 270, 110, 32);

        lblIP18.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lblIP18.setForeground(new java.awt.Color(255, 255, 255));
        lblIP18.setText("Fecha de fin:");
        add(lblIP18);
        lblIP18.setBounds(40, 670, 150, 30);

        panelCantidadPrecio.setBackground(new Color(0, 0, 0, 0));
        panelCantidadPrecio.setOpaque(false);
        panelCantidadPrecio.setLayout(new java.awt.GridLayout(2, 2, 10, 30));

        lblIP14.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lblIP14.setForeground(new java.awt.Color(255, 255, 255));
        lblIP14.setText("MAX.Alumnos:");
        panelCantidadPrecio.add(lblIP14);

        capacidad.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        capacidad.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                capacidadStateChanged(evt);
            }
        });
        panelCantidadPrecio.add(capacidad);

        lblIP19.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lblIP19.setForeground(new java.awt.Color(255, 255, 255));
        lblIP19.setText("Precio:              $");
        panelCantidadPrecio.add(lblIP19);

        spinnerPrecio.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        spinnerPrecio.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                spinnerPrecioStateChanged(evt);
            }
        });
        panelCantidadPrecio.add(spinnerPrecio);

        add(panelCantidadPrecio);
        panelCantidadPrecio.setBounds(40, 980, 300, 110);

        btnGuardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Utilerias/botones/btnGuardar.png"))); // NOI18N
        btnGuardar.setBorderPainted(false);
        btnGuardar.setContentAreaFilled(false);
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });
        add(btnGuardar);
        btnGuardar.setBounds(860, 1190, 270, 70);

        btnRegresar2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Utilerias/botones/btnRegresarClase.png"))); // NOI18N
        btnRegresar2.setBorderPainted(false);
        btnRegresar2.setContentAreaFilled(false);
        btnRegresar2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegresar2ActionPerformed(evt);
            }
        });
        add(btnRegresar2);
        btnRegresar2.setBounds(60, 1180, 270, 80);

        panelAula.setBackground(new Color(0, 0, 0, 0));
        panelAula.setOpaque(false);
        panelAula.setLayout(new java.awt.GridLayout(2, 1, 3, 0));

        lblIP20.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lblIP20.setForeground(new java.awt.Color(255, 255, 255));
        lblIP20.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblIP20.setText("Aula:");
        panelAula.add(lblIP20);

        comboxAulas.setFont(new java.awt.Font("Dialog", 1, 18));
        comboxAulas.setForeground(new java.awt.Color(30, 47, 86));
        comboxAulas.setModel(new javax.swing.DefaultComboBoxModel<>());
        comboxAulas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboxAulasActionPerformed(evt);
            }
        });
        panelAula.add(comboxAulas);

        add(panelAula);
        panelAula.setBounds(1080, 140, 230, 80);
    }// </editor-fold>//GEN-END:initComponents

    private void comboxMaestroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboxMaestroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboxMaestroActionPerformed

    private void checkBoxLunActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkBoxLunActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_checkBoxLunActionPerformed

    private void checkBoxMarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkBoxMarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_checkBoxMarActionPerformed

    private void checkBoxMieActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkBoxMieActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_checkBoxMieActionPerformed

    private void checkBoxJueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkBoxJueActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_checkBoxJueActionPerformed

    private void checkBoxVieActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkBoxVieActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_checkBoxVieActionPerformed

    private void checkBoxSabActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkBoxSabActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_checkBoxSabActionPerformed

    private void checkBoxDomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkBoxDomActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_checkBoxDomActionPerformed

    private void jCalendarFechaInicioPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_jCalendarFechaInicioPropertyChange
        if (evt.getOldValue() != null) {
            Date fechaSeleccionada = jCalendarFechaInicio.getDate();
            if (fechaSeleccionada != null) {
                LocalDate fechaInicio = fechaSeleccionada.toInstant()
                        .atZone(ZoneId.systemDefault())
                        .toLocalDate();
                System.out.println("Fecha inicio: " + fechaInicio);
                this.fechaInicio = fechaInicio;
            }
        }
    }//GEN-LAST:event_jCalendarFechaInicioPropertyChange

    private void jCalendarFechaFinPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_jCalendarFechaFinPropertyChange
        // TODO add your handling code here:
        if (evt.getOldValue() != null) {
            Date fechaSeleccionada = jCalendarFechaFin.getDate();
            if (fechaSeleccionada != null) {
                LocalDate fechaFin = fechaSeleccionada.toInstant()
                        .atZone(ZoneId.systemDefault())
                        .toLocalDate();
                System.out.println("Fecha Fin: " + fechaFin);
                this.fechaFin = fechaFin;
            }
        }
    }//GEN-LAST:event_jCalendarFechaFinPropertyChange

    private void spinnerHoraInicioStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_spinnerHoraInicioStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_spinnerHoraInicioStateChanged

    private void spinnerMinutosInicioStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_spinnerMinutosInicioStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_spinnerMinutosInicioStateChanged

    private void spinnerHoraFinStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_spinnerHoraFinStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_spinnerHoraFinStateChanged

    private void spinnerMinutosFinStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_spinnerMinutosFinStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_spinnerMinutosFinStateChanged

    private void capacidadStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_capacidadStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_capacidadStateChanged

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        // TODO add your handling code here:
        diasSeleccionados = new ArrayList<>();
        
        for (JCheckBox checkBox : dias) {
            if (checkBox.isSelected()) {
                diasSeleccionados.add(mapaDias.get(checkBox));
            }
        }
                
//Datos
        //Nombre clase 
        String nombreClase = txtNomClase.getText().trim();
        //Maestro
        MaestroDTO maestroSeleccionado = (MaestroDTO) comboxMaestro.getSelectedItem();
        //Modalidad 
        String modalidadSeleccionada = (String) comboxModalidad.getSelectedItem();
        //Aula
        AulaClaseDTO aulaSeleccionada = (AulaClaseDTO) comboxAulas.getSelectedItem();

        //Horas
        // Obtener hora y minuto desde los spinners personalizados
        int horaInicio = (int) spinnerHoraInicio.getValue();
        int minutoInicio = (int) spinnerMinutosInicio.getValue();

// Crear un objeto LocalTime
        LocalTime horaInicioCompleta = LocalTime.of(horaInicio, minutoInicio);
        
        //Hora FIN
        int horaFin = (int) spinnerHoraFin.getValue();
        int minutoFin = (int) spinnerMinutosFin.getValue();

        LocalTime horaFinCompleta = LocalTime.of(horaFin, minutoFin);
        
        //capacidad y Precio
        int capacidad = (int) this.capacidad.getValue();
        double precio = (double) spinnerPrecio.getValue();
        
        //crear objeto dto
        NuevaClaseDTO nuevaClase = new NuevaClaseDTO(
                nombreClase, maestroSeleccionado, modalidadSeleccionada, 
                aulaSeleccionada, diasSeleccionados, 
                horaInicioCompleta, horaFinCompleta, 
                fechaInicio, fechaFin, capacidad, precio, true);
        
        System.out.println(nuevaClase.toString());
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void txtNomClaseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtNomClaseMouseClicked
        // TODO add your handling code here:
        txtNomClase.setText("");
    }//GEN-LAST:event_txtNomClaseMouseClicked

    private void comboxModalidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboxModalidadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboxModalidadActionPerformed

    private void comboxAulasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboxAulasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboxAulasActionPerformed

    private void spinnerPrecioStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_spinnerPrecioStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_spinnerPrecioStateChanged

    private void btnRegresar2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresar2ActionPerformed
        // TODO add your handling code here:
        //Regresar a administracion Clases
    }//GEN-LAST:event_btnRegresar2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel ComboxPanel;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnRegresar2;
    private javax.swing.JSpinner capacidad;
    private javax.swing.JCheckBox checkBoxDom;
    private javax.swing.JCheckBox checkBoxJue;
    private javax.swing.JCheckBox checkBoxLun;
    private javax.swing.JCheckBox checkBoxMar;
    private javax.swing.JCheckBox checkBoxMie;
    private javax.swing.JCheckBox checkBoxSab;
    private javax.swing.JCheckBox checkBoxVie;
    private javax.swing.JComboBox<AulaClaseDTO> comboxAulas;
    private javax.swing.JComboBox<MaestroDTO> comboxMaestro;
    private javax.swing.JComboBox<String> comboxModalidad;
    private javax.swing.JPanel diasClasesPanel;
    private com.toedter.calendar.JCalendar jCalendarFechaFin;
    private com.toedter.calendar.JCalendar jCalendarFechaInicio;
    private javax.swing.JLabel lblHora;
    private javax.swing.JLabel lblHora1;
    private javax.swing.JLabel lblIP;
    private javax.swing.JLabel lblIP1;
    private javax.swing.JLabel lblIP10;
    private javax.swing.JLabel lblIP11;
    private javax.swing.JLabel lblIP12;
    private javax.swing.JLabel lblIP13;
    private javax.swing.JLabel lblIP14;
    private javax.swing.JLabel lblIP15;
    private javax.swing.JLabel lblIP16;
    private javax.swing.JLabel lblIP17;
    private javax.swing.JLabel lblIP18;
    private javax.swing.JLabel lblIP19;
    private javax.swing.JLabel lblIP2;
    private javax.swing.JLabel lblIP20;
    private javax.swing.JLabel lblIP3;
    private javax.swing.JLabel lblIP4;
    private javax.swing.JLabel lblIP5;
    private javax.swing.JLabel lblIP6;
    private javax.swing.JLabel lblIP7;
    private javax.swing.JLabel lblIP8;
    private javax.swing.JLabel lblIP9;
    private javax.swing.JPanel panelAula;
    private javax.swing.JPanel panelCantidadPrecio;
    private javax.swing.JPanel panelDatosClase;
    private javax.swing.JPanel panelDatosMaestro;
    private javax.swing.JPanel panelHoraFin;
    private javax.swing.JPanel panelHoraInicio;
    private javax.swing.JPanel panelModalidad;
    private javax.swing.JSpinner spinnerHoraFin;
    private javax.swing.JSpinner spinnerHoraInicio;
    private javax.swing.JSpinner spinnerMinutosFin;
    private javax.swing.JSpinner spinnerMinutosInicio;
    private javax.swing.JSpinner spinnerPrecio;
    private javax.swing.JTextField txtNomClase;
    // End of variables declaration//GEN-END:variables
}
