/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package FRMs.GestionarClases;

import DTOs.GestionarClases.AulaClaseDTO;
import DTOs.GestionarClases.MaestroDTO;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JFrame;
import javax.swing.SwingUtilities;

/**
 *
 * @author Jack Murrieta
 */
public class PanelScrollGuardarClase extends javax.swing.JPanel {

    private PanelGuardarClase panelGuardarClase;

    public PanelScrollGuardarClase(List<MaestroDTO> maestros, List<AulaClaseDTO> aulas) {
        initComponents();

        // Instanciar el panel que irá dentro del JScrollPane
        PanelGuardarClase panelGuardarClase = new PanelGuardarClase(maestros, aulas);

        // Establecer el panel dentro del scroll
        jScrollPane.setViewportView(panelGuardarClase);
    }

    public static void main(String[] args) {
        SwingUtilities.invokeLater(() -> {
            JFrame frame = new JFrame("Prueba DatosClaseScroll");

            // Crear y llenar la lista de aulas
            List<AulaClaseDTO> aulas = new ArrayList<>();
            aulas.add(new AulaClaseDTO("A1", "Laboratorio 1"));
            aulas.add(new AulaClaseDTO("A2", "Sala de Conferencias"));
            aulas.add(new AulaClaseDTO("A3", "Aula 302"));

            // Crear y llenar la lista de maestros
            List<MaestroDTO> maestros = new ArrayList<>();
            maestros.add(new MaestroDTO("M1", "Juan Pérez"));
            maestros.add(new MaestroDTO("M2", "Laura Gómez"));
            maestros.add(new MaestroDTO("M3", "Carlos Ruiz"));

            // Crear el panel con scroll
            PanelScrollGuardarClase datosClaseScroll = new PanelScrollGuardarClase(maestros, aulas);

            // Suponiendo que tienes un método en PanelScrollGuardarClase para cargar datos:

            // Agregar el panel al JFrame
            frame.getContentPane().add(datosClaseScroll);

            // Configurar el frame
            frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
            frame.setSize(1230, 1300);
            frame.setLocationRelativeTo(null); // Centra la ventana
            frame.setVisible(true);
        });

    }
    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane = new javax.swing.JScrollPane();

        setLayout(new java.awt.BorderLayout());

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Registrar Clase");
        add(jLabel1, java.awt.BorderLayout.PAGE_START);
        add(jScrollPane, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane;
    // End of variables declaration//GEN-END:variables
}
