/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package FRMs.GestionarClases;

import java.awt.Color;
import java.awt.Dimension;
import java.awt.Graphics;
import java.awt.Image;
import java.time.LocalDate;
import javax.swing.ImageIcon;
import DTOs.GestionarClases.EditarClaseDTO;
import java.time.ZoneId;
import java.util.Date;
import FRMs.GestionarClases.CustomHoraMinutoSpinner.Tipo;
import com.mycompany.presentacion.ControlNavegacion;
import java.time.LocalTime;

/**
 *
 * @author Jack Murrieta
 */
public class PanelEditarClase extends javax.swing.JPanel {

    private Image imagenFondo;
    private LocalDate fechaFin;
    private EditarClaseDTO claseEditarDTO;
    private boolean activa;

    /**
     * Creates new form AdminClases
     *
     * @param claseEditarDTO
     */
    public PanelEditarClase(EditarClaseDTO claseEditarDTO) {
        this.claseEditarDTO = claseEditarDTO;
        // Carga la imagen de fondo
        this.imagenFondo = new ImageIcon(getClass().getResource("/Utilerias/FondoCERO.jpeg")).getImage();
        initComponents();
        setOpaque(false); // Asegura que el fondo se pinte correctamente
        setPreferredSize(new Dimension(1230, 1300));
        //Configurar labels
        //informacion general
        lblClaseNombre.setText(claseEditarDTO.getNombreClase());
        lblNombreMaestro.setText(claseEditarDTO.getMaestro().getNombreCompleto());
        lblAula.setText(claseEditarDTO.getAula().getNombreAula());
        lblDias.setText(claseEditarDTO.getDiasStr());

        //horario 
        //dias de la semana
        //fecha inicio y hora inicio
        lblFechaInicio.setText(claseEditarDTO.getFechaInicioStr());
        lblHoraInicio.setText(claseEditarDTO.getHoraInicioStr());
        lblPrecio.setText(claseEditarDTO.getPrecio());
        activa = true;
        //capacidad
        capacidad.setValue(claseEditarDTO.getCuposDisponibles());
    }

    @Override
    protected void paintComponent(Graphics g) {
        super.paintComponent(g);
        // Dibuja la imagen de fondo
        g.drawImage(imagenFondo, 0, 0, getWidth(), getHeight(), this);
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelDatosMaestro = new javax.swing.JPanel();
        lblIP3 = new javax.swing.JLabel();
        lblNombreMaestro = new javax.swing.JLabel();
        lblIP1 = new javax.swing.JLabel();
        panelDatosClase = new javax.swing.JPanel();
        lblIP2 = new javax.swing.JLabel();
        lblClaseNombre = new javax.swing.JLabel();
        lblIP4 = new javax.swing.JLabel();
        lblIP5 = new javax.swing.JLabel();
        diasClasesPanel = new javax.swing.JPanel();
        panelModalidad = new javax.swing.JPanel();
        lblIP = new javax.swing.JLabel();
        lblModalidad = new javax.swing.JLabel();
        lblIP13 = new javax.swing.JLabel();
        jCalendarFechaFin = new com.toedter.calendar.JCalendar();
        lblIP15 = new javax.swing.JLabel();
        lblIP16 = new javax.swing.JLabel();
        panelHoraInicio = new javax.swing.JPanel();
        lblHoraInicio = new javax.swing.JLabel();
        panelHoraFin = new javax.swing.JPanel();
        spinnerHoraFin = new FRMs.GestionarClases.CustomHoraMinutoSpinner(Tipo.HORA);
        lblHoraSeparacion = new javax.swing.JLabel();
        spinnerMinutosFin = new FRMs.GestionarClases.CustomHoraMinutoSpinner(Tipo.MINUTO);
        lblIP17 = new javax.swing.JLabel();
        lblIP18 = new javax.swing.JLabel();
        panelCantidadPrecio = new javax.swing.JPanel();
        lblIP14 = new javax.swing.JLabel();
        capacidad = new CustomCapacidadSpinner();
        lblIP19 = new javax.swing.JLabel();
        lblPrecio = new javax.swing.JLabel();
        btnInactivarClase = new javax.swing.JButton();
        btnRegresar = new javax.swing.JButton();
        panelAula = new javax.swing.JPanel();
        lblIP20 = new javax.swing.JLabel();
        lblAula = new javax.swing.JLabel();
        lblFechaInicio = new javax.swing.JLabel();
        btnGuardar = new javax.swing.JButton();
        lblDias = new javax.swing.JLabel();

        setLayout(null);

        panelDatosMaestro.setBackground(new Color(0, 0, 0, 0));
        panelDatosMaestro.setOpaque(false);
        panelDatosMaestro.setLayout(new java.awt.GridLayout(2, 1));

        lblIP3.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lblIP3.setForeground(new java.awt.Color(255, 255, 255));
        lblIP3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblIP3.setText("Maestro:");
        panelDatosMaestro.add(lblIP3);

        lblNombreMaestro.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lblNombreMaestro.setForeground(new java.awt.Color(30, 47, 86));
        lblNombreMaestro.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblNombreMaestro.setText("nombre");
        panelDatosMaestro.add(lblNombreMaestro);

        add(panelDatosMaestro);
        panelDatosMaestro.setBounds(420, 140, 270, 80);

        lblIP1.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        lblIP1.setForeground(new java.awt.Color(30, 47, 86));
        lblIP1.setText("Capacidad y Precio:");
        add(lblIP1);
        lblIP1.setBounds(40, 930, 230, 32);

        panelDatosClase.setBackground(new Color(0, 0, 0, 0));
        panelDatosClase.setOpaque(false);
        panelDatosClase.setLayout(new java.awt.GridLayout(2, 1, 3, 0));

        lblIP2.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lblIP2.setForeground(new java.awt.Color(255, 255, 255));
        lblIP2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblIP2.setText("Nombre Clase:");
        panelDatosClase.add(lblIP2);

        lblClaseNombre.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lblClaseNombre.setForeground(new java.awt.Color(30, 47, 86));
        lblClaseNombre.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblClaseNombre.setText("PROGRAMACION");
        panelDatosClase.add(lblClaseNombre);

        add(panelDatosClase);
        panelDatosClase.setBounds(80, 140, 290, 80);

        lblIP4.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        lblIP4.setForeground(new java.awt.Color(30, 47, 86));
        lblIP4.setText("Informacion General:");
        add(lblIP4);
        lblIP4.setBounds(40, 80, 280, 46);

        lblIP5.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lblIP5.setForeground(new java.awt.Color(255, 255, 255));
        lblIP5.setText("Hora Fin:");
        add(lblIP5);
        lblIP5.setBounds(560, 670, 150, 30);

        diasClasesPanel.setBackground(new Color(0, 0, 0, 0));
        diasClasesPanel.setOpaque(false);
        diasClasesPanel.setLayout(new java.awt.GridLayout(1, 7, 5, 5));
        add(diasClasesPanel);
        diasClasesPanel.setBounds(190, 300, 470, 30);

        panelModalidad.setBackground(new Color(0, 0, 0, 0));
        panelModalidad.setOpaque(false);
        panelModalidad.setLayout(new java.awt.GridLayout(2, 1, 3, 0));

        lblIP.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lblIP.setForeground(new java.awt.Color(255, 255, 255));
        lblIP.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblIP.setText("Modalidad:");
        panelModalidad.add(lblIP);

        lblModalidad.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lblModalidad.setForeground(new java.awt.Color(30, 47, 86));
        lblModalidad.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblModalidad.setText("Presencial");
        panelModalidad.add(lblModalidad);

        add(panelModalidad);
        panelModalidad.setBounds(750, 140, 290, 80);

        lblIP13.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lblIP13.setForeground(new java.awt.Color(255, 255, 255));
        lblIP13.setText("Dias de clases:");
        add(lblIP13);
        lblIP13.setBounds(40, 320, 140, 30);

        jCalendarFechaFin.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                jCalendarFechaFinPropertyChange(evt);
            }
        });
        add(jCalendarFechaFin);
        jCalendarFechaFin.setBounds(140, 720, 270, 200);

        lblIP15.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lblIP15.setForeground(new java.awt.Color(255, 255, 255));
        lblIP15.setText("Fecha de inicio:");
        add(lblIP15);
        lblIP15.setBounds(40, 490, 150, 30);

        lblIP16.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lblIP16.setForeground(new java.awt.Color(255, 255, 255));
        lblIP16.setText("Hora inicio:");
        add(lblIP16);
        lblIP16.setBounds(560, 400, 150, 30);

        panelHoraInicio.setBackground(new Color(0, 0, 0, 0));
        panelHoraInicio.setOpaque(false);
        panelHoraInicio.setLayout(new java.awt.GridLayout(1, 2, 0, 30));

        lblHoraInicio.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        lblHoraInicio.setForeground(new java.awt.Color(30, 47, 86));
        lblHoraInicio.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblHoraInicio.setText("04:00");
        panelHoraInicio.add(lblHoraInicio);

        add(panelHoraInicio);
        panelHoraInicio.setBounds(560, 450, 370, 50);

        panelHoraFin.setBackground(new Color(0, 0, 0, 0));
        panelHoraFin.setOpaque(false);
        panelHoraFin.setLayout(new java.awt.GridLayout(1, 2, 0, 30));

        spinnerHoraFin.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        spinnerHoraFin.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                spinnerHoraFinStateChanged(evt);
            }
        });
        panelHoraFin.add(spinnerHoraFin);

        lblHoraSeparacion.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        lblHoraSeparacion.setForeground(new java.awt.Color(30, 47, 86));
        lblHoraSeparacion.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblHoraSeparacion.setText(":");
        panelHoraFin.add(lblHoraSeparacion);

        spinnerMinutosFin.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        spinnerMinutosFin.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                spinnerMinutosFinStateChanged(evt);
            }
        });
        panelHoraFin.add(spinnerMinutosFin);

        add(panelHoraFin);
        panelHoraFin.setBounds(560, 730, 380, 50);

        lblIP17.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        lblIP17.setForeground(new java.awt.Color(30, 47, 86));
        lblIP17.setText("Horario:");
        add(lblIP17);
        lblIP17.setBounds(40, 270, 110, 32);

        lblIP18.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lblIP18.setForeground(new java.awt.Color(255, 255, 255));
        lblIP18.setText("Fecha de fin:");
        add(lblIP18);
        lblIP18.setBounds(40, 670, 150, 30);

        panelCantidadPrecio.setBackground(new Color(0, 0, 0, 0));
        panelCantidadPrecio.setOpaque(false);
        panelCantidadPrecio.setLayout(new java.awt.GridLayout(2, 2, 10, 30));

        lblIP14.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lblIP14.setForeground(new java.awt.Color(255, 255, 255));
        lblIP14.setText("MAX.Alumnos:");
        panelCantidadPrecio.add(lblIP14);

        capacidad.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        capacidad.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                capacidadStateChanged(evt);
            }
        });
        panelCantidadPrecio.add(capacidad);

        lblIP19.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lblIP19.setForeground(new java.awt.Color(255, 255, 255));
        lblIP19.setText("Precio:              $");
        panelCantidadPrecio.add(lblIP19);

        lblPrecio.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        lblPrecio.setForeground(new java.awt.Color(30, 47, 86));
        lblPrecio.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        panelCantidadPrecio.add(lblPrecio);

        add(panelCantidadPrecio);
        panelCantidadPrecio.setBounds(40, 980, 300, 110);

        btnInactivarClase.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Utilerias/botones/btnInactivarClaseEditar.png"))); // NOI18N
        btnInactivarClase.setBorderPainted(false);
        btnInactivarClase.setContentAreaFilled(false);
        btnInactivarClase.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInactivarClaseActionPerformed(evt);
            }
        });
        add(btnInactivarClase);
        btnInactivarClase.setBounds(860, 1040, 270, 70);

        btnRegresar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Utilerias/botones/btnRegresarClase.png"))); // NOI18N
        btnRegresar.setBorderPainted(false);
        btnRegresar.setContentAreaFilled(false);
        btnRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegresarActionPerformed(evt);
            }
        });
        add(btnRegresar);
        btnRegresar.setBounds(60, 1180, 270, 80);

        panelAula.setBackground(new Color(0, 0, 0, 0));
        panelAula.setOpaque(false);
        panelAula.setLayout(new java.awt.GridLayout(2, 1, 3, 0));

        lblIP20.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lblIP20.setForeground(new java.awt.Color(255, 255, 255));
        lblIP20.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblIP20.setText("Aula:");
        panelAula.add(lblIP20);

        lblAula.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lblAula.setForeground(new java.awt.Color(30, 47, 86));
        lblAula.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblAula.setText("Presencial");
        panelAula.add(lblAula);

        add(panelAula);
        panelAula.setBounds(1080, 140, 230, 80);

        lblFechaInicio.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        lblFechaInicio.setForeground(new java.awt.Color(30, 47, 86));
        lblFechaInicio.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblFechaInicio.setText("1/01/2025");
        add(lblFechaInicio);
        lblFechaInicio.setBounds(200, 480, 220, 60);

        btnGuardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Utilerias/botones/btnGuardar.png"))); // NOI18N
        btnGuardar.setBorderPainted(false);
        btnGuardar.setContentAreaFilled(false);
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });
        add(btnGuardar);
        btnGuardar.setBounds(860, 1170, 270, 90);

        lblDias.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lblDias.setForeground(new java.awt.Color(30, 47, 86));
        lblDias.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblDias.setText("DOM");
        add(lblDias);
        lblDias.setBounds(190, 320, 470, 30);
    }// </editor-fold>//GEN-END:initComponents

    private void jCalendarFechaFinPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_jCalendarFechaFinPropertyChange
        // TODO add your handling code here:
        if (evt.getOldValue() != null) {
            Date fechaSeleccionada = jCalendarFechaFin.getDate();
            if (fechaSeleccionada != null) {
                LocalDate fechaFin = fechaSeleccionada.toInstant()
                        .atZone(ZoneId.systemDefault())
                        .toLocalDate();
                this.fechaFin = fechaFin;
            }
        }
    }//GEN-LAST:event_jCalendarFechaFinPropertyChange

    private void capacidadStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_capacidadStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_capacidadStateChanged

    private void btnInactivarClaseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInactivarClaseActionPerformed
        // TODO add your handling code here:
        //la clase es activa por defecto

        if (activa) {
            activa = false;
            this.claseEditarDTO.setActiva(false);
            btnInactivarClase.setIcon(new javax.swing.ImageIcon(
                    getClass().getResource("/Utilerias/botones/btnActivarClase.png")
            ));
        } else {
            activa = true;
            this.claseEditarDTO.setActiva(true);
            btnInactivarClase.setIcon(new javax.swing.ImageIcon(
                    getClass().getResource("/Utilerias/botones/btnInactivarClaseEditar.png")
            ));
        }

    }//GEN-LAST:event_btnInactivarClaseActionPerformed

    private void btnRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresarActionPerformed
        // TODO add your handling code here:
        ControlNavegacion.mostrarFrmAdminClases();
        //Regresar a administracion Clases
    }//GEN-LAST:event_btnRegresarActionPerformed

    private void spinnerMinutosFinStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_spinnerMinutosFinStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_spinnerMinutosFinStateChanged

    private void spinnerHoraFinStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_spinnerHoraFinStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_spinnerHoraFinStateChanged

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        // TODO add your handling code here:

        // Crear un objeto LocalTime
         // Obtener valores spinners
        int horaFin = (int) spinnerHoraFin.getValue();
        int minutoFin = (int) spinnerMinutosFin.getValue();

        LocalTime horaFinCompleta = LocalTime.of(horaFin, minutoFin);

// Obtener otros datos
        int capacidad = (int) this.capacidad.getValue();

        //settear valores
        this.claseEditarDTO.setHoraFin(horaFinCompleta);
        this.claseEditarDTO.setCapacidadAlumnos(capacidad);
        this.claseEditarDTO.setFechaFin(fechaFin);
        this.claseEditarDTO.setActiva(activa);

        ControlNavegacion.editarClase(claseEditarDTO);
    }//GEN-LAST:event_btnGuardarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnInactivarClase;
    private javax.swing.JButton btnRegresar;
    private javax.swing.JSpinner capacidad;
    private javax.swing.JPanel diasClasesPanel;
    private com.toedter.calendar.JCalendar jCalendarFechaFin;
    private javax.swing.JLabel lblAula;
    private javax.swing.JLabel lblClaseNombre;
    private javax.swing.JLabel lblDias;
    private javax.swing.JLabel lblFechaInicio;
    private javax.swing.JLabel lblHoraInicio;
    private javax.swing.JLabel lblHoraSeparacion;
    private javax.swing.JLabel lblIP;
    private javax.swing.JLabel lblIP1;
    private javax.swing.JLabel lblIP13;
    private javax.swing.JLabel lblIP14;
    private javax.swing.JLabel lblIP15;
    private javax.swing.JLabel lblIP16;
    private javax.swing.JLabel lblIP17;
    private javax.swing.JLabel lblIP18;
    private javax.swing.JLabel lblIP19;
    private javax.swing.JLabel lblIP2;
    private javax.swing.JLabel lblIP20;
    private javax.swing.JLabel lblIP3;
    private javax.swing.JLabel lblIP4;
    private javax.swing.JLabel lblIP5;
    private javax.swing.JLabel lblModalidad;
    private javax.swing.JLabel lblNombreMaestro;
    private javax.swing.JLabel lblPrecio;
    private javax.swing.JPanel panelAula;
    private javax.swing.JPanel panelCantidadPrecio;
    private javax.swing.JPanel panelDatosClase;
    private javax.swing.JPanel panelDatosMaestro;
    private javax.swing.JPanel panelHoraFin;
    private javax.swing.JPanel panelHoraInicio;
    private javax.swing.JPanel panelModalidad;
    private javax.swing.JSpinner spinnerHoraFin;
    private javax.swing.JSpinner spinnerMinutosFin;
    // End of variables declaration//GEN-END:variables
}
