package FRM.GestionarAlumnos;

import com.mycompany.dtos.AlumnoDTO;
import com.mycompany.presentacion.ControlNavegacion;
import com.mycompany.presentacion.excepciones.PresentacionException;
import java.awt.BorderLayout;
import java.awt.Graphics;
import java.awt.Image;
import java.time.LocalDate;
import java.time.ZoneId;
import java.util.Date;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JPanel;

/**
 *
 * @author Jack Murrieta
 */
public class FrmRegistrarNuevoAlumno extends javax.swing.JFrame {

    private Image imagenFondo;

    /**
     * Creates new form FrmClasesExistentes
     *
     * 
     */
    public FrmRegistrarNuevoAlumno() {
        initComponents();

        // Cargar la imagen de fondo
        this.imagenFondo = new ImageIcon(getClass().getResource("/Utilerias/FondoCERO.jpeg")).getImage();

        // Sobrescribir el paintComponent del panelFondo ya creado en initComponents
        panelFondo = new JPanel(new BorderLayout(10, 0)) {
            @Override
            protected void paintComponent(Graphics g) {
                super.paintComponent(g);
                g.drawImage(imagenFondo, 0, 0, getWidth(), getHeight(), this);
            }
        };

        // Reaplicar los paneles a panelFondo con transparencia
        panelFondo.add(Header, BorderLayout.PAGE_START);
        panelFondo.add(panelScroll, BorderLayout.CENTER);
        panelFondo.add(panelBotones, BorderLayout.PAGE_END);

        // Hacer todos los paneles hijos transparentes
        hacerPanelesTransparentes();

        // Usar panelFondo como contenido principal del JFrame
        setContentPane(panelFondo);

        // Configuración del frame
        setTitle("Registrar alumno");
        setSize(1300, 500);
        setLocationRelativeTo(null);
        setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        setVisible(true);

    }

    private void hacerPanelesTransparentes() {
        Header.setOpaque(false);
        panelFiltros.setOpaque(false);
        panelBusqueda.setOpaque(false);
        panelTipoFiltro.setOpaque(false);
        panelBotones.setOpaque(false);
        panelBtnAñadir.setOpaque(false);
        panelBtnRegresar.setOpaque(false);
        panelScroll.setOpaque(false);
        panelScroll.setOpaque(false);
        panelScroll.setOpaque(false);
    }

 


    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelFondo = new javax.swing.JPanel();
        Header = new javax.swing.JPanel();
        lblTitulo = new javax.swing.JLabel();
        panelFiltros = new javax.swing.JPanel();
        panelBusqueda = new javax.swing.JPanel();
        campoVacio = new javax.swing.JLabel();
        lblNombreClase2 = new javax.swing.JLabel();
        panelTipoFiltro = new javax.swing.JPanel();
        campoVacio2 = new javax.swing.JLabel();
        campoVacio3 = new javax.swing.JLabel();
        panelBotones = new javax.swing.JPanel();
        panelBtnRegresar = new javax.swing.JPanel();
        jButton5 = new javax.swing.JButton();
        panelBtnAñadir = new javax.swing.JPanel();
        btnNuevoEstudiante = new javax.swing.JButton();
        panelScroll = new javax.swing.JPanel();
        lblIP2 = new javax.swing.JLabel();
        txtApellidoP = new javax.swing.JTextField();
        lblIP3 = new javax.swing.JLabel();
        lblIP5 = new javax.swing.JLabel();
        txtApellidoM = new javax.swing.JTextField();
        lblIP4 = new javax.swing.JLabel();
        lblIP6 = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        lblIP7 = new javax.swing.JLabel();
        lblIP8 = new javax.swing.JLabel();
        selectorFecha = new com.toedter.calendar.JDateChooser();
        lblIP10 = new javax.swing.JLabel();
        lblIP11 = new javax.swing.JLabel();
        txtTelefono = new javax.swing.JTextField();
        lblIP14 = new javax.swing.JLabel();
        lblIP15 = new javax.swing.JLabel();
        txtCorreo = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panelFondo.setLayout(new java.awt.BorderLayout(10, 0));

        Header.setLayout(new java.awt.BorderLayout(10, 40));

        lblTitulo.setFont(new java.awt.Font("Menlo", 1, 48));
        lblTitulo.setForeground(new java.awt.Color(30, 47, 86));
        lblTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitulo.setText("REGISTRAR ALUMNO");
        Header.add(lblTitulo, java.awt.BorderLayout.PAGE_START);

        panelFiltros.setLayout(new java.awt.GridLayout(2, 1, 10, 25));

        panelBusqueda.setLayout(new java.awt.GridLayout(1, 3, 40, 0));

        campoVacio.setFont(new java.awt.Font("Menlo", 1, 24)); // NOI18N
        campoVacio.setForeground(new java.awt.Color(30, 47, 86));
        campoVacio.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        panelBusqueda.add(campoVacio);

        lblNombreClase2.setFont(new java.awt.Font("Menlo", 1, 24)); // NOI18N
        lblNombreClase2.setForeground(new java.awt.Color(30, 47, 86));
        lblNombreClase2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        panelBusqueda.add(lblNombreClase2);

        panelFiltros.add(panelBusqueda);

        panelTipoFiltro.setLayout(new java.awt.GridLayout(1, 3, 40, 5));

        campoVacio2.setFont(new java.awt.Font("Menlo", 1, 24)); // NOI18N
        campoVacio2.setForeground(new java.awt.Color(30, 47, 86));
        campoVacio2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        panelTipoFiltro.add(campoVacio2);

        campoVacio3.setFont(new java.awt.Font("Menlo", 1, 24)); // NOI18N
        campoVacio3.setForeground(new java.awt.Color(30, 47, 86));
        campoVacio3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        panelTipoFiltro.add(campoVacio3);

        panelFiltros.add(panelTipoFiltro);

        Header.add(panelFiltros, java.awt.BorderLayout.CENTER);

        panelFondo.add(Header, java.awt.BorderLayout.PAGE_START);

        panelBotones.setLayout(new java.awt.BorderLayout());

        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Utilerias/botones/btnRegresarClase.png"))); // NOI18N
        jButton5.setBorderPainted(false);
        jButton5.setContentAreaFilled(false);
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelBtnRegresarLayout = new javax.swing.GroupLayout(panelBtnRegresar);
        panelBtnRegresar.setLayout(panelBtnRegresarLayout);
        panelBtnRegresarLayout.setHorizontalGroup(
            panelBtnRegresarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBtnRegresarLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jButton5)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelBtnRegresarLayout.setVerticalGroup(
            panelBtnRegresarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelBtnRegresarLayout.createSequentialGroup()
                .addContainerGap(17, Short.MAX_VALUE)
                .addComponent(jButton5)
                .addGap(14, 14, 14))
        );

        panelBotones.add(panelBtnRegresar, java.awt.BorderLayout.LINE_START);

        btnNuevoEstudiante.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Utilerias/botones/btnAñadirAlumno.png"))); // NOI18N
        btnNuevoEstudiante.setBorderPainted(false);
        btnNuevoEstudiante.setContentAreaFilled(false);
        btnNuevoEstudiante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevoEstudianteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelBtnAñadirLayout = new javax.swing.GroupLayout(panelBtnAñadir);
        panelBtnAñadir.setLayout(panelBtnAñadirLayout);
        panelBtnAñadirLayout.setHorizontalGroup(
            panelBtnAñadirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBtnAñadirLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnNuevoEstudiante, javax.swing.GroupLayout.PREFERRED_SIZE, 281, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelBtnAñadirLayout.setVerticalGroup(
            panelBtnAñadirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelBtnAñadirLayout.createSequentialGroup()
                .addContainerGap(17, Short.MAX_VALUE)
                .addComponent(btnNuevoEstudiante, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15))
        );

        panelBotones.add(panelBtnAñadir, java.awt.BorderLayout.LINE_END);

        panelFondo.add(panelBotones, java.awt.BorderLayout.PAGE_END);

        panelScroll.setLayout(new java.awt.GridLayout(6, 4, 15, 5));

        lblIP2.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lblIP2.setForeground(new java.awt.Color(255, 255, 255));
        lblIP2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblIP2.setText("Apellido Paterno:");
        panelScroll.add(lblIP2);

        txtApellidoP.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtApellidoP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtApellidoPActionPerformed(evt);
            }
        });
        panelScroll.add(txtApellidoP);

        lblIP3.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lblIP3.setForeground(new java.awt.Color(255, 255, 255));
        lblIP3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        panelScroll.add(lblIP3);

        lblIP5.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lblIP5.setForeground(new java.awt.Color(255, 255, 255));
        lblIP5.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblIP5.setText("Apellido Materno:");
        panelScroll.add(lblIP5);

        txtApellidoM.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        panelScroll.add(txtApellidoM);

        lblIP4.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lblIP4.setForeground(new java.awt.Color(255, 255, 255));
        lblIP4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        panelScroll.add(lblIP4);

        lblIP6.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lblIP6.setForeground(new java.awt.Color(255, 255, 255));
        lblIP6.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblIP6.setText("Nombres(s):");
        panelScroll.add(lblIP6);

        txtNombre.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtNombre.setText(" ");
        txtNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreActionPerformed(evt);
            }
        });
        panelScroll.add(txtNombre);

        lblIP7.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lblIP7.setForeground(new java.awt.Color(255, 255, 255));
        lblIP7.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        panelScroll.add(lblIP7);

        lblIP8.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lblIP8.setForeground(new java.awt.Color(255, 255, 255));
        lblIP8.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblIP8.setText("Fecha de Nacimiento:");
        panelScroll.add(lblIP8);
        panelScroll.add(selectorFecha);

        lblIP10.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lblIP10.setForeground(new java.awt.Color(255, 255, 255));
        lblIP10.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        panelScroll.add(lblIP10);

        lblIP11.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lblIP11.setForeground(new java.awt.Color(255, 255, 255));
        lblIP11.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblIP11.setText("Telefono de contacto:");
        panelScroll.add(lblIP11);

        txtTelefono.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtTelefono.setText(" ");
        panelScroll.add(txtTelefono);

        lblIP14.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lblIP14.setForeground(new java.awt.Color(255, 255, 255));
        lblIP14.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        panelScroll.add(lblIP14);

        lblIP15.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lblIP15.setForeground(new java.awt.Color(255, 255, 255));
        lblIP15.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblIP15.setText("Correo Electronico:");
        panelScroll.add(lblIP15);

        txtCorreo.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtCorreo.setText(" ");
        panelScroll.add(txtCorreo);

        panelFondo.add(panelScroll, java.awt.BorderLayout.CENTER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelFondo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panelFondo, javax.swing.GroupLayout.PREFERRED_SIZE, 695, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        this.dispose();
        ControlNavegacion.mostrarFrmAdminAlumnos();

    }//GEN-LAST:event_jButton5ActionPerformed

    private void btnNuevoEstudianteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoEstudianteActionPerformed
        // TODO add your handling code here:
        String apellidoPaterno = txtApellidoP.getText().trim();
        String apellidoMaterno = txtApellidoM.getText().trim();
        String nombre = txtNombre.getText().trim();
        Date fechaSeleccionada = selectorFecha.getDate();
        String telefono = txtTelefono.getText().trim();
        String correoElectronico = txtCorreo.getText().trim();
        
        // Validar formato de fecha
        if(fechaSeleccionada != null){
        LocalDate fechaNacimientoDate = fechaSeleccionada.toInstant().atZone(ZoneId.systemDefault()).toLocalDate();

        // Crear alumnoDTO solo si la fecha fue válida
        AlumnoDTO nuevoAlumnoDTO = new AlumnoDTO(apellidoPaterno, apellidoMaterno, nombre, telefono, fechaNacimientoDate, correoElectronico);
        ControlNavegacion.registrarNuevoAlumno(nuevoAlumnoDTO);
        }else{
            ControlNavegacion.mostrarMensajeErrorConExcepcion(this, new PresentacionException("Campos vacios"));
        }
        
    }//GEN-LAST:event_btnNuevoEstudianteActionPerformed

    private void txtApellidoPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtApellidoPActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtApellidoPActionPerformed

    private void txtNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Header;
    private javax.swing.JButton btnNuevoEstudiante;
    private javax.swing.JLabel campoVacio;
    private javax.swing.JLabel campoVacio2;
    private javax.swing.JLabel campoVacio3;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel lblIP10;
    private javax.swing.JLabel lblIP11;
    private javax.swing.JLabel lblIP14;
    private javax.swing.JLabel lblIP15;
    private javax.swing.JLabel lblIP2;
    private javax.swing.JLabel lblIP3;
    private javax.swing.JLabel lblIP4;
    private javax.swing.JLabel lblIP5;
    private javax.swing.JLabel lblIP6;
    private javax.swing.JLabel lblIP7;
    private javax.swing.JLabel lblIP8;
    private javax.swing.JLabel lblNombreClase2;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JPanel panelBotones;
    private javax.swing.JPanel panelBtnAñadir;
    private javax.swing.JPanel panelBtnRegresar;
    private javax.swing.JPanel panelBusqueda;
    private javax.swing.JPanel panelFiltros;
    private javax.swing.JPanel panelFondo;
    private javax.swing.JPanel panelScroll;
    private javax.swing.JPanel panelTipoFiltro;
    private com.toedter.calendar.JDateChooser selectorFecha;
    private javax.swing.JTextField txtApellidoM;
    private javax.swing.JTextField txtApellidoP;
    private javax.swing.JTextField txtCorreo;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtTelefono;
    // End of variables declaration//GEN-END:variables
}
