package FRMs.GaleriaContenidos;

import com.mycompany.dtos.ClaseDTO;
import com.mycompany.presentacion.ControlNavegacion;
import javax.swing.SwingUtilities;
import javax.swing.text.SimpleAttributeSet;
import javax.swing.text.StyleConstants;
import javax.swing.text.StyledDocument;

/**
 *
 * @author daniel
 */
public class PnlClaseExistente extends javax.swing.JPanel {

    private ClaseDTO clase;
    
    /**
     * Creates new form PnlClaseExistente
     */
    public PnlClaseExistente(ClaseDTO clase) {
        initComponents();
        this.clase = clase;
        
        txfId.setText(clase.getCodigo().toString());
        txpNombreClase.setText(clase.getNombre());
        txpMaestro.setText(clase.getMaestro());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txfId = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txpNombreClase = new javax.swing.JTextPane();
        jScrollPane2 = new javax.swing.JScrollPane();
        txpHorario = new javax.swing.JTextPane();
        jScrollPane3 = new javax.swing.JScrollPane();
        txpMaestro = new javax.swing.JTextPane();

        setBackground(new java.awt.Color(30, 47, 86));
        setMaximumSize(new java.awt.Dimension(871, 97));
        setMinimumSize(new java.awt.Dimension(871, 97));

        txfId.setEditable(false);
        txfId.setBackground(new java.awt.Color(30, 47, 86));
        txfId.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        txfId.setForeground(new java.awt.Color(255, 255, 255));
        txfId.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txfId.setBorder(null);

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Utilerias/botones/btnSeleccionarClaseGC.png"))); // NOI18N
        jButton1.setBorder(null);
        jButton1.setContentAreaFilled(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jScrollPane1.setBackground(new java.awt.Color(30, 47, 86));
        jScrollPane1.setBorder(null);
        jScrollPane1.setToolTipText("ytntntyn");

        txpNombreClase.setEditable(false);
        txpNombreClase.setBackground(new java.awt.Color(30, 47, 86));
        txpNombreClase.setBorder(null);
        txpNombreClase.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        txpNombreClase.setForeground(new java.awt.Color(255, 255, 255));
        txpNombreClase.setText("Contemporáneo Principiante");
        txpNombreClase.setMaximumSize(new java.awt.Dimension(138, 50));
        txpNombreClase.setSelectedTextColor(new java.awt.Color(30, 47, 86));
        jScrollPane1.setViewportView(txpNombreClase);
        StyledDocument docNombreClase = txpNombreClase.getStyledDocument();
        docNombreClase.setParagraphAttributes(
            0, docNombreClase.getLength(),
            new SimpleAttributeSet() {{
                StyleConstants.setAlignment(this, StyleConstants.ALIGN_CENTER);
            }},
            false
        );

        jScrollPane2.setBorder(null);
        jScrollPane2.setToolTipText("ytntntyn");

        txpHorario.setEditable(false);
        txpHorario.setBackground(new java.awt.Color(30, 47, 86));
        txpHorario.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        txpHorario.setForeground(new java.awt.Color(255, 255, 255));
        txpHorario.setText("LuMiVi 1:00-2:30");
        txpHorario.setMaximumSize(new java.awt.Dimension(154, 29));
        txpHorario.setMinimumSize(new java.awt.Dimension(154, 29));
        jScrollPane2.setViewportView(txpHorario);
        StyledDocument docHorario = txpHorario.getStyledDocument();
        //
        docHorario.setParagraphAttributes(
            0, docHorario.getLength(),
            new SimpleAttributeSet() {{
                StyleConstants.setAlignment(this, StyleConstants.ALIGN_CENTER);
            }},
            false
        );

        jScrollPane3.setBorder(null);
        jScrollPane3.setToolTipText("ytntntyn");

        txpMaestro.setEditable(false);
        txpMaestro.setBackground(new java.awt.Color(30, 47, 86));
        txpMaestro.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        txpMaestro.setForeground(new java.awt.Color(255, 255, 255));
        txpMaestro.setText("César");
        txpMaestro.setMaximumSize(new java.awt.Dimension(257, 29));
        txpMaestro.setMinimumSize(new java.awt.Dimension(257, 29));
        jScrollPane3.setViewportView(txpMaestro);
        StyledDocument docMaestro = txpMaestro.getStyledDocument();
        docMaestro.setParagraphAttributes(
            0, docMaestro.getLength(),
            new SimpleAttributeSet() {{
                StyleConstants.setAlignment(this, StyleConstants.ALIGN_CENTER);
            }},
            false
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addComponent(txfId, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 183, Short.MAX_VALUE)
                .addGap(41, 41, 41))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 97, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(txfId, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addComponent(jScrollPane3)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        ControlNavegacion.seleccionarClaseGC(clase);
        ControlNavegacion.mostrarFrmContenidos();
        SwingUtilities.getWindowAncestor(this).dispose();
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextField txfId;
    private javax.swing.JTextPane txpHorario;
    private javax.swing.JTextPane txpMaestro;
    private javax.swing.JTextPane txpNombreClase;
    // End of variables declaration//GEN-END:variables
}
