package FRMs;

import com.mycompany.dtos.AlumnoDTO;
import com.mycompany.dtos.ClaseDTO;
import com.mycompany.presentacion.ControlNavegacion;
import java.awt.Graphics;
import java.awt.Image;
import java.util.List;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JPanel;
import javax.swing.JTextField;
import org.netbeans.lib.awtextra.AbsoluteConstraints;
import org.netbeans.lib.awtextra.AbsoluteLayout;

/**
 *
 * @author daniel
 */
public class FrmAlumnosInscritos extends javax.swing.JFrame {

    private Image imagenFondo;
    private ClaseDTO clase;

    /**
     * Creates new form FrmAlumnosInscritos
     */
    public FrmAlumnosInscritos(List<AlumnoDTO> alumnos, ClaseDTO clase) {
        this.clase = clase;
        
        initComponents();
        int totalInscripciones = 0;
        int numeroLista = 0;
        for (AlumnoDTO alumnoDTO : alumnos) {
            numeroLista++;
            crearDatosClase(alumnoDTO, numeroLista);
            totalInscripciones++;
        }
        txfTotalInscripciones.setText(Integer.toString(totalInscripciones));
        
        
        this.setTitle("Finalizar Inscripcion");

        this.imagenFondo = new ImageIcon(getClass().getResource("/Utilerias/FondoCERO.jpeg")).getImage();
        JPanel pnlFondo = new JPanel() {
            @Override
            protected void paintComponent(Graphics g) {
                super.paintComponent(g);
                g.drawImage(imagenFondo, 0, 0, getWidth(), getHeight(), this);
            }
        };

        this.getContentPane().setLayout(new AbsoluteLayout());
        this.getContentPane().add(pnlFondo, new AbsoluteConstraints(0, 0, 1000, 700));

        this.setSize(1000, 700); 
        this.setLocationRelativeTo(null); 
        this.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        PanelContenedor = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txfTotalInscripciones = new javax.swing.JTextField();
        txfCapacidadGrupo = new javax.swing.JTextField();
        txfCuposDisponibles = new javax.swing.JTextField();
        btnRegresar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setIconImages(null);

        PanelContenedor.setBackground(new java.awt.Color(30, 47, 86));
        PanelContenedor.setLayout(new javax.swing.BoxLayout(PanelContenedor, javax.swing.BoxLayout.Y_AXIS));

        jPanel9.setBackground(new java.awt.Color(30, 47, 86));
        jPanel9.setMaximumSize(new java.awt.Dimension(526, 50));
        jPanel9.setMinimumSize(new java.awt.Dimension(526, 50));
        jPanel9.setName(""); // NOI18N
        jPanel9.setPreferredSize(new java.awt.Dimension(526, 50));

        jLabel18.setFont(new java.awt.Font("Kohinoor Bangla", 1, 14)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(148, 197, 227));
        jLabel18.setText("ID ALUMNO");

        jLabel19.setFont(new java.awt.Font("Kohinoor Bangla", 1, 14)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(148, 197, 227));
        jLabel19.setText("NUMERO DE LISTA");

        jLabel20.setFont(new java.awt.Font("Kohinoor Bangla", 1, 14)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(148, 197, 227));
        jLabel20.setText("NOMBRE");

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel19)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 108, Short.MAX_VALUE)
                .addComponent(jLabel18)
                .addGap(105, 105, 105)
                .addComponent(jLabel20)
                .addGap(42, 42, 42))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        PanelContenedor.add(jPanel9);

        jScrollPane1.setViewportView(PanelContenedor);

        jLabel9.setFont(new java.awt.Font("Kohinoor Telugu", 1, 48)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(30, 47, 86));
        jLabel9.setText("ALUMNOS INSCRITOS");

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Cupos disponibles");
        jLabel1.setOpaque(false);

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Capacidad del grupo");
        jLabel2.setOpaque(false);

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Total de inscripciones");
        jLabel3.setOpaque(false);

        txfTotalInscripciones.setEditable(false);
        txfTotalInscripciones.setBackground(new java.awt.Color(0, 0, 0, 0));
        txfTotalInscripciones.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        txfTotalInscripciones.setForeground(new java.awt.Color(255, 255, 255));
        txfTotalInscripciones.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txfTotalInscripciones.setText("0");
        txfTotalInscripciones.setBorder(null);
        txfTotalInscripciones.setOpaque(false);

        txfCapacidadGrupo.setEditable(false);
        txfCapacidadGrupo.setBackground(new java.awt.Color(0, 0, 0, 0));
        txfCapacidadGrupo.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        txfCapacidadGrupo.setForeground(new java.awt.Color(255, 255, 255));
        txfCapacidadGrupo.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txfCapacidadGrupo.setText("0");
        txfCapacidadGrupo.setBorder(null);
        txfCapacidadGrupo.setOpaque(false);

        txfCuposDisponibles.setEditable(false);
        txfCuposDisponibles.setBackground(new java.awt.Color(0, 0, 0, 0));
        txfCuposDisponibles.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        txfCuposDisponibles.setForeground(new java.awt.Color(255, 255, 255));
        txfCuposDisponibles.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txfCuposDisponibles.setText("0");
        txfCuposDisponibles.setBorder(null);
        txfCuposDisponibles.setOpaque(false);

        btnRegresar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Utilerias/botones/regresar.png"))); // NOI18N
        btnRegresar.setBorder(null);
        btnRegresar.setContentAreaFilled(false);
        btnRegresar.setOpaque(false);
        btnRegresar.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Utilerias/botones/regresarHovered.png"))); // NOI18N
        btnRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegresarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(237, 237, 237)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 548, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(197, 197, 197)
                                .addComponent(txfCapacidadGrupo, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(137, 137, 137)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(56, 56, 56)
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(39, 39, 39)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(97, 97, 97)
                                .addComponent(txfTotalInscripciones, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txfCuposDisponibles, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(378, 378, 378)
                        .addComponent(btnRegresar))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(258, 258, 258)
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 492, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(344, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jLabel9)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 277, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(47, 47, 47)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txfCapacidadGrupo, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txfTotalInscripciones, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txfCuposDisponibles, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addComponent(btnRegresar)
                .addContainerGap(408, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresarActionPerformed
        ControlNavegacion.mostrarDatosClase(clase);
        this.dispose();
    }//GEN-LAST:event_btnRegresarActionPerformed

    private void crearDatosClase(AlumnoDTO alumnoDTO, int numeroLista) {
        JPanel PanelNuevo = new javax.swing.JPanel();
        JTextField txfNumeroLista = new javax.swing.JTextField();
        JTextField txfNombre = new javax.swing.JTextField();
        JTextField txfIDAlumno = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setIconImages(null);

        PanelNuevo.setBackground(new java.awt.Color(30, 47, 86));
        PanelNuevo.setMaximumSize(new java.awt.Dimension(526, 30));
        PanelNuevo.setMinimumSize(new java.awt.Dimension(526, 30));

        txfNumeroLista.setEditable(false);
        txfNumeroLista.setBackground(new java.awt.Color(30, 47, 86));
        txfNumeroLista.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txfNumeroLista.setForeground(new java.awt.Color(255, 255, 255));
        txfNumeroLista.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txfNumeroLista.setBorder(null);
        txfNumeroLista.setOpaque(false);

        txfIDAlumno.setEditable(false);
        txfIDAlumno.setBackground(new java.awt.Color(30, 47, 86));
        txfIDAlumno.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txfIDAlumno.setForeground(new java.awt.Color(255, 255, 255));
        txfIDAlumno.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txfIDAlumno.setBorder(null);
        txfIDAlumno.setOpaque(false);

        txfNombre.setEditable(false);
        txfNombre.setBackground(new java.awt.Color(30, 47, 86));
        txfNombre.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txfNombre.setForeground(new java.awt.Color(255, 255, 255));
        txfNombre.setHorizontalAlignment(javax.swing.JTextField.LEADING);
        txfNombre.setBorder(null);
        txfNombre.setOpaque(false);

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(PanelNuevo);
        PanelNuevo.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(txfNumeroLista, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(txfIDAlumno, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(txfNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(55, Short.MAX_VALUE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txfIDAlumno, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txfNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txfNumeroLista, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addComponent(PanelNuevo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 862, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(394, 394, 394)
                .addComponent(PanelNuevo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(628, Short.MAX_VALUE))
        );

        txfNombre.setText(alumnoDTO.getNombre() + " " +
                          alumnoDTO.getApellidoPaterno() + " " + alumnoDTO.getApellidoMaterno());
        txfIDAlumno.setText(Integer.toString(alumnoDTO.getCodigo()));
        txfNumeroLista.setText(String.format("%02d", numeroLista));
        pack();
        
        PanelContenedor.add(PanelNuevo);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PanelContenedor;
    private javax.swing.JButton btnRegresar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField txfCapacidadGrupo;
    private javax.swing.JTextField txfCuposDisponibles;
    private javax.swing.JTextField txfTotalInscripciones;
    // End of variables declaration//GEN-END:variables
}
