/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package FRMs;

import Utilerias.RenderTabla;
import java.awt.Graphics;
import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Usuario
 */
public class FrmClasesExistentes extends javax.swing.JFrame {

    private Image imagenFondo;

    /**
     * Creates new form FrmClasesExistentes
     */
    public FrmClasesExistentes() {
        initComponents();
        this.setTitle("Clases Existentes");
        this.imagenFondo = new ImageIcon(getClass().getResource("/Utilerias/FondoCERO.jpeg")).getImage();

        // Crear un JPanel con la imagen de fondo y agregarlo al frame
        JPanel jPanel1 = new JPanel() {
            @Override
            protected void paintComponent(Graphics g) {
                super.paintComponent(g);
                g.drawImage(imagenFondo, 0, 0, getWidth(), getHeight(), this);
            }
        };

        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 900, 600));
        pack();
        //
        llenarClasesExistentes();

    }

    private void llenarClasesExistentes() {
        DefaultTableModel modelo = new DefaultTableModel() {
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        };
        // Lista de clases hardcodeadas con un arreglo de Object
        // Jackkkkk, este es un método que tienes que llamar desde el control del InscribirClase :P
        Object[][] clases = {
            {1, "Contemporanea", "08:00 - 10:00"+System.lineSeparator()+"LUN-MIE-VIE", "Profesor A"},
            {2, "Contemporanea", "10:00 - 12:00,MAR-JUEV", "Profesor B"},
            {3, "Contemporanea", "12:00 - 14:00,MAR-JUEV", "Profesor C"}
        };

        modelo.setColumnIdentifiers(new Object[]{"ID Clase", "Nombre Clase", "Horario", "Maestro", "Seleccionar"});
       
        //CAMBIARAN POR DTOS
        for (Object[] clase : clases) {
            JButton btn = crearBotonSeleccionar((int) clase[0]);
            modelo.addRow(new Object[]{
                clase[0],
                clase[1],
                clase[2],
                clase[3],
                btn
            });
        }
        tblClasesExistentes.setModel(modelo);
        tblClasesExistentes.getColumn("Seleccionar").setCellRenderer(new RenderTabla());
        tblClasesExistentes.setRowHeight(50);
        tblClasesExistentes.getColumnModel().getColumn(2).setPreferredWidth(200);
        
    }

    private JButton crearBotonSeleccionar(int id) {
        JButton btnSeleccionar = new JButton("Seleccionar");
        return btnSeleccionar;
    }

    //METODO SELECCIONAR CLASE AL CLICKEAR BTN
    private void seleccionarClase(int idClase) {
        System.out.println(idClase);

    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblClasesExistentes = new javax.swing.JTable();
        btnRegresar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Menlo", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(30, 47, 86));
        jLabel1.setText("CLASES EXISTENTES");

        tblClasesExistentes.setBackground(new java.awt.Color(30, 47, 86));
        tblClasesExistentes.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        tblClasesExistentes.setForeground(new java.awt.Color(255, 255, 255));
        tblClasesExistentes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID Clase", "Nombre Clase", "Horario", "Maestro", "Seleccionar"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblClasesExistentes.setRowHeight(50);
        tblClasesExistentes.setRowMargin(15);
        tblClasesExistentes.setSelectionBackground(new java.awt.Color(0, 102, 153));
        tblClasesExistentes.setShowGrid(false);
        tblClasesExistentes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblClasesExistentesMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblClasesExistentes);
        if (tblClasesExistentes.getColumnModel().getColumnCount() > 0) {
            tblClasesExistentes.getColumnModel().getColumn(0).setResizable(false);
            tblClasesExistentes.getColumnModel().getColumn(1).setResizable(false);
            tblClasesExistentes.getColumnModel().getColumn(2).setResizable(false);
            tblClasesExistentes.getColumnModel().getColumn(3).setResizable(false);
        }

        btnRegresar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Utilerias/botones/btnRegresar.png"))); // NOI18N
        btnRegresar.setBorderPainted(false);
        btnRegresar.setContentAreaFilled(false);
        btnRegresar.setFocusPainted(false);
        btnRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegresarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(191, 191, 191)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(34, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 817, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(35, 35, 35))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnRegresar, javax.swing.GroupLayout.PREFERRED_SIZE, 292, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(288, 288, 288))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 365, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnRegresar, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(40, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    private void tblClasesExistentesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblClasesExistentesMouseClicked
        // TODO add your handling code here:
        int column = this.tblClasesExistentes.getColumnModel().getColumnIndexAtX(evt.getX());
        int row = evt.getY() / this.tblClasesExistentes.getRowHeight();

        if (row < this.tblClasesExistentes.getRowCount() && row >= 0 && column < this.tblClasesExistentes.getColumnCount() && column >= 0) {
            Object value = this.tblClasesExistentes.getValueAt(row, column);
            if (value instanceof JButton) {
                JButton boton = (JButton) value;
                int idClase = (int) this.tblClasesExistentes.getValueAt(row, 0);

                if (boton.getText().equals("Seleccionar")) {
                    seleccionarClase(idClase);
                }
            }
        }

    }//GEN-LAST:event_tblClasesExistentesMouseClicked

    private void btnRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresarActionPerformed
        // TODO add your handling code here:
        System.out.println("Regresar");
    }//GEN-LAST:event_btnRegresarActionPerformed

    /**
         * @param args the command line arguments
         */
    public static void main(String args[]){
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmClasesExistentes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmClasesExistentes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmClasesExistentes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmClasesExistentes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmClasesExistentes().setVisible(true);
            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRegresar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblClasesExistentes;
    // End of variables declaration//GEN-END:variables
}
