package FRMs;

import com.mycompany.dtos.AlumnoBusquedaDTO;
import com.mycompany.dtos.ClaseDTO;
import Presentacion.ControlNavegacion;
import Excepciones.PresentacionException;
import java.awt.Graphics;
import java.awt.Image;
import java.time.DayOfWeek;
import java.time.format.DateTimeFormatter;
import java.util.List;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JPanel;

/**
 *
 * @author Carlos
 */
public class FrmDatosClase extends javax.swing.JFrame {

    private Image imagenFondo;
    private ClaseDTO clase;
    private AlumnoBusquedaDTO alumnoBusqueda;

    /**
     * Creates new form FrmDatosClase
     */
    public FrmDatosClase(ClaseDTO claseDTO) {
        initComponents();
        this.clase = claseDTO;
        this.setTitle("Datos Clase");
        this.imagenFondo = new ImageIcon(getClass().getResource("/Utilerias/FondoCERO.jpeg")).getImage();

        // Crear un JPanel con la imagen de fondo y agregarlo al frame
        JPanel jPanel1 = new JPanel() {
            @Override
            protected void paintComponent(Graphics g) {
                super.paintComponent(g);
                g.drawImage(imagenFondo, 0, 0, getWidth(), getHeight(), this);
            }
        };

        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1000, 700));

        this.setSize(1000, 700); // Ajusta el tamaño del JFrame
        this.setLocationRelativeTo(null); // Centra la ventana en la pantalla
        this.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);

        lblIDClase.setText(Integer.toString(claseDTO.getCodigo()));
        lblNombreClase.setText(claseDTO.getNombre());
        lblHorarioClase.setText(claseDTO.getNombre());

        DateTimeFormatter formatoHora = DateTimeFormatter.ofPattern("HH:mm");

        List<DayOfWeek> diasSemana = claseDTO.getDias();  // Lista de DayOfWeek
        StringBuilder diasAbreviados = new StringBuilder();

        for (DayOfWeek dia : diasSemana) {
            // Tomamos las dos primeras letras del nombre en español
            diasAbreviados.append(dia.getDisplayName(java.time.format.TextStyle.SHORT, new java.util.Locale("es")).substring(0, 2));
        }

        String horario = String.format("%s %s %s",
                diasAbreviados.toString(),
                claseDTO.getHoraInicio().format(formatoHora),
                claseDTO.getHoraFin().format(formatoHora));

        lblHorarioClase.setText(horario);

        System.out.println(lblHorarioClase.getText());
        lblMaestro.setText(claseDTO.getMaestro());
        lblPrecio.setText(claseDTO.getPrecio().toString());

        pack();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelDatosClase = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        lblIDClase = new javax.swing.JTextField();
        lblPrecio = new javax.swing.JTextField();
        lblHorarioClase = new javax.swing.JTextField();
        lblMaestro = new javax.swing.JTextField();
        lblNombreClase = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        btnVerAlumnosInscritos = new javax.swing.JButton();
        btnRegresar = new javax.swing.JButton();
        btnRegistrarAlumno = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        btnInscribirAlumno = new javax.swing.JButton();
        txtCodigoAlumno = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(865, 654));
        setSize(new java.awt.Dimension(865, 654));

        PanelDatosClase.setBackground(new java.awt.Color(30, 47, 86));
        PanelDatosClase.setForeground(new java.awt.Color(30, 47, 86));

        jLabel3.setFont(new java.awt.Font("Menlo", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(148, 197, 227));
        jLabel3.setText("ID CLASE");

        jLabel5.setFont(new java.awt.Font("Menlo", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(148, 197, 227));
        jLabel5.setText("PRECIO");

        jLabel6.setFont(new java.awt.Font("Menlo", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(148, 197, 227));
        jLabel6.setText("NOMBRE CLASE");

        jLabel7.setFont(new java.awt.Font("Menlo", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(148, 197, 227));
        jLabel7.setText("HORARIO");

        jLabel8.setFont(new java.awt.Font("Menlo", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(148, 197, 227));
        jLabel8.setText("MAESTRO");

        lblIDClase.setEditable(false);
        lblIDClase.setBackground(new java.awt.Color(30, 47, 86));
        lblIDClase.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblIDClase.setForeground(new java.awt.Color(255, 255, 255));
        lblIDClase.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        lblIDClase.setText("ID");
        lblIDClase.setBorder(null);

        lblPrecio.setEditable(false);
        lblPrecio.setBackground(new java.awt.Color(30, 47, 86));
        lblPrecio.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblPrecio.setForeground(new java.awt.Color(255, 255, 255));
        lblPrecio.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        lblPrecio.setText("PRECIO");
        lblPrecio.setBorder(null);

        lblHorarioClase.setEditable(false);
        lblHorarioClase.setBackground(new java.awt.Color(30, 47, 86));
        lblHorarioClase.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblHorarioClase.setForeground(new java.awt.Color(255, 255, 255));
        lblHorarioClase.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        lblHorarioClase.setText("NOMBRE");
        lblHorarioClase.setBorder(null);

        lblMaestro.setEditable(false);
        lblMaestro.setBackground(new java.awt.Color(30, 47, 86));
        lblMaestro.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblMaestro.setForeground(new java.awt.Color(255, 255, 255));
        lblMaestro.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        lblMaestro.setText("MAESTRO");
        lblMaestro.setBorder(null);

        lblNombreClase.setEditable(false);
        lblNombreClase.setBackground(new java.awt.Color(30, 47, 86));
        lblNombreClase.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblNombreClase.setForeground(new java.awt.Color(255, 255, 255));
        lblNombreClase.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        lblNombreClase.setText("NOMBRE");
        lblNombreClase.setBorder(null);

        javax.swing.GroupLayout PanelDatosClaseLayout = new javax.swing.GroupLayout(PanelDatosClase);
        PanelDatosClase.setLayout(PanelDatosClaseLayout);
        PanelDatosClaseLayout.setHorizontalGroup(
            PanelDatosClaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelDatosClaseLayout.createSequentialGroup()
                .addGroup(PanelDatosClaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelDatosClaseLayout.createSequentialGroup()
                        .addGap(55, 55, 55)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(47, 47, 47))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelDatosClaseLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblIDClase, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(32, 32, 32)))
                .addGroup(PanelDatosClaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelDatosClaseLayout.createSequentialGroup()
                        .addComponent(lblNombreClase, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblHorarioClase, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29)
                        .addComponent(lblMaestro, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26))
                    .addGroup(PanelDatosClaseLayout.createSequentialGroup()
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(60, 60, 60)
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(61, 61, 61)
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 60, Short.MAX_VALUE)
                        .addComponent(jLabel5)
                        .addGap(56, 56, 56))))
        );
        PanelDatosClaseLayout.setVerticalGroup(
            PanelDatosClaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelDatosClaseLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanelDatosClaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PanelDatosClaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblIDClase, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblHorarioClase, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblMaestro, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblNombreClase, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(16, Short.MAX_VALUE))
        );

        jLabel4.setFont(new java.awt.Font("Menlo", 1, 48)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(30, 47, 86));
        jLabel4.setText("DATOS DE LA CLASE");

        btnVerAlumnosInscritos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Utilerias/botones/verAlumnosInscritos.png"))); // NOI18N
        btnVerAlumnosInscritos.setBorder(null);
        btnVerAlumnosInscritos.setContentAreaFilled(false);
        btnVerAlumnosInscritos.setOpaque(false);
        btnVerAlumnosInscritos.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Utilerias/botones/verAlumnosInscritosHovered.png"))); // NOI18N
        btnVerAlumnosInscritos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVerAlumnosInscritosActionPerformed(evt);
            }
        });

        btnRegresar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Utilerias/botones/regresar.png"))); // NOI18N
        btnRegresar.setBorder(null);
        btnRegresar.setContentAreaFilled(false);
        btnRegresar.setOpaque(false);
        btnRegresar.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Utilerias/botones/regresarHovered.png"))); // NOI18N
        btnRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegresarActionPerformed(evt);
            }
        });

        btnRegistrarAlumno.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Utilerias/botones/registrarNuevoAlumno.png"))); // NOI18N
        btnRegistrarAlumno.setBorder(null);
        btnRegistrarAlumno.setContentAreaFilled(false);
        btnRegistrarAlumno.setOpaque(false);
        btnRegistrarAlumno.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Utilerias/botones/registrarNuevoAlumnoHovered.png"))); // NOI18N
        btnRegistrarAlumno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarAlumnoActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Menlo", 1, 24)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("ID alumno:");

        btnInscribirAlumno.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Utilerias/botones/inscribirAlumno.png"))); // NOI18N
        btnInscribirAlumno.setBorder(null);
        btnInscribirAlumno.setContentAreaFilled(false);
        btnInscribirAlumno.setOpaque(false);
        btnInscribirAlumno.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Utilerias/botones/inscribirAlumnoHovered.png"))); // NOI18N
        btnInscribirAlumno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInscribirAlumnoActionPerformed(evt);
            }
        });

        txtCodigoAlumno.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        txtCodigoAlumno.setBorder(null);
        txtCodigoAlumno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCodigoAlumnoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(261, 261, 261)
                        .addComponent(jLabel4))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(306, 306, 306)
                        .addComponent(btnVerAlumnosInscritos))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(130, 130, 130)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnRegresar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnRegistrarAlumno))
                            .addComponent(PanelDatosClase, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addGap(31, 31, 31)
                                .addComponent(txtCodigoAlumno, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(42, 42, 42)
                                .addComponent(btnInscribirAlumno)))))
                .addContainerGap(379, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(PanelDatosClase, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnVerAlumnosInscritos)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnInscribirAlumno))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(71, 71, 71)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtCodigoAlumno, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(22, 22, 22)))
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnRegistrarAlumno)
                    .addComponent(btnRegresar))
                .addContainerGap(215, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnVerAlumnosInscritosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerAlumnosInscritosActionPerformed
        ControlNavegacion.mostrarAlumnosInscritos(clase);
    }//GEN-LAST:event_btnVerAlumnosInscritosActionPerformed

    private void btnRegistrarAlumnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarAlumnoActionPerformed
        try {
            ControlNavegacion.mostrarRegistrarAlumno(clase);
            this.dispose();
        } catch (PresentacionException ex) {
            ControlNavegacion.mostrarMensajeErrorConExcepcion(this, ex);
        }
    }//GEN-LAST:event_btnRegistrarAlumnoActionPerformed

    private void btnRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresarActionPerformed

        ControlNavegacion.mostrarClasesExistente(clase.getNombre());
        this.dispose();

    }//GEN-LAST:event_btnRegresarActionPerformed

    private void btnInscribirAlumnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInscribirAlumnoActionPerformed

        // obtenerInfo de txt
        String campo = txtCodigoAlumno.getText().trim();
        ControlNavegacion.mostrarErrorcampoIdAlumno(campo);
        this.dispose();
        ControlNavegacion.mostrarFinalizarInscripcion(this.clase, campo);
    }//GEN-LAST:event_btnInscribirAlumnoActionPerformed

    private void txtCodigoAlumnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCodigoAlumnoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCodigoAlumnoActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PanelDatosClase;
    private javax.swing.JButton btnInscribirAlumno;
    private javax.swing.JButton btnRegistrarAlumno;
    private javax.swing.JButton btnRegresar;
    private javax.swing.JButton btnVerAlumnosInscritos;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField lblHorarioClase;
    private javax.swing.JTextField lblIDClase;
    private javax.swing.JTextField lblMaestro;
    private javax.swing.JTextField lblNombreClase;
    private javax.swing.JTextField lblPrecio;
    private javax.swing.JTextField txtCodigoAlumno;
    // End of variables declaration//GEN-END:variables
}
