package FRMs;

import com.mycompany.negocio.dtos.ClaseDTO;
import java.awt.Graphics;
import java.awt.Image;
import java.math.BigDecimal;
import java.time.DayOfWeek;
import java.time.LocalTime;
import java.time.format.DateTimeFormatter;
import java.util.Arrays;
import java.util.List;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JPanel;

/**
 *
 * @author daniel
 */
public class FrmFinalizarInscripcion extends javax.swing.JFrame {

    private Image imagenFondo;

    /**
     * Creates new customizer FrmFinalizarInscripcion
     */
    public FrmFinalizarInscripcion(ClaseDTO claseDTO) {
        initComponents();
        this.setTitle("Finalizar Inscripcion");

        // Cargar la imagen de fondo 
        this.imagenFondo = new ImageIcon(getClass().getResource("/Utilerias/FondoCERO.jpeg")).getImage();

        // Crear un JPanel con la imagen de fondo y lo agrega al frame
        JPanel jPanel1 = new javax.swing.JPanel() {
            @Override
            protected void paintComponent(Graphics g) {
                super.paintComponent(g);
                g.drawImage(imagenFondo, 0, 0, getWidth(), getHeight(), this);
            }
        };

        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1000, 700));

        this.setSize(1000, 700); // Ajusta el tamaño del JFrame
        this.setLocationRelativeTo(null); // Centra la ventana en la pantalla
        this.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);

        txfIDClase.setText(Integer.toString(claseDTO.getCodigo()));
        txfNombreClase.setText(claseDTO.getNombre());

        DateTimeFormatter formatoHora = DateTimeFormatter.ofPattern("HH:mm");

        List<DayOfWeek> diasSemana = claseDTO.getDias();  // Lista de DayOfWeek
        StringBuilder diasAbreviados = new StringBuilder();

        for (DayOfWeek dia : diasSemana) {
            // Tomamos las dos primeras letras del nombre en español
            diasAbreviados.append(dia.getDisplayName(java.time.format.TextStyle.SHORT, new java.util.Locale("es")).substring(0, 2));
        }

        String horario = String.format("%s %s %s",
                diasAbreviados.toString(),
                claseDTO.getHoraInicio().format(formatoHora),
                claseDTO.getHoraFin().format(formatoHora));

        txfHorarioClase.setText(horario);

        System.out.println(txfHorarioClase.getText());
        txfMaestro.setText(claseDTO.getMaestro());
        txfPrecio.setText(claseDTO.getPrecio().toString());

        pack();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the FormEditor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txfIDClase = new javax.swing.JTextField();
        txfNombreClase = new javax.swing.JTextField();
        txfHorarioClase = new javax.swing.JTextField();
        txfMaestro = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txfPrecio = new javax.swing.JTextField();
        jButton4 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        b = new javax.swing.JButton();

        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(30, 47, 86));
        jPanel1.setForeground(new java.awt.Color(30, 47, 86));

        jLabel3.setFont(new java.awt.Font("Menlo", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(148, 197, 227));
        jLabel3.setText("ID CLASE");

        jLabel6.setFont(new java.awt.Font("Menlo", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(148, 197, 227));
        jLabel6.setText("NOMBRE CLASE");

        jLabel7.setFont(new java.awt.Font("Menlo", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(148, 197, 227));
        jLabel7.setText("HORARIO");

        jLabel8.setFont(new java.awt.Font("Menlo", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(148, 197, 227));
        jLabel8.setText("MAESTRO");

        txfIDClase.setEditable(false);
        txfIDClase.setBackground(new java.awt.Color(30, 47, 86));
        txfIDClase.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txfIDClase.setForeground(new java.awt.Color(255, 255, 255));
        txfIDClase.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txfIDClase.setText("ID");
        txfIDClase.setToolTipText("");
        txfIDClase.setBorder(null);
        txfIDClase.setOpaque(false);

        txfNombreClase.setEditable(false);
        txfNombreClase.setBackground(new java.awt.Color(30, 47, 86));
        txfNombreClase.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txfNombreClase.setForeground(new java.awt.Color(255, 255, 255));
        txfNombreClase.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txfNombreClase.setText("NOMBRE");
        txfNombreClase.setBorder(null);
        txfNombreClase.setOpaque(false);

        txfHorarioClase.setEditable(false);
        txfHorarioClase.setBackground(new java.awt.Color(30, 47, 86));
        txfHorarioClase.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txfHorarioClase.setForeground(new java.awt.Color(255, 255, 255));
        txfHorarioClase.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txfHorarioClase.setText("NOMBRE");
        txfHorarioClase.setBorder(null);
        txfHorarioClase.setOpaque(false);

        txfMaestro.setEditable(false);
        txfMaestro.setBackground(new java.awt.Color(30, 47, 86));
        txfMaestro.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txfMaestro.setForeground(new java.awt.Color(255, 255, 255));
        txfMaestro.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txfMaestro.setText("NOMBRE");
        txfMaestro.setBorder(null);
        txfMaestro.setOpaque(false);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(txfIDClase, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(37, 37, 37)
                        .addComponent(txfNombreClase, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(58, 58, 58)
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(txfHorarioClase, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27)
                        .addComponent(txfMaestro, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(56, 56, 56)
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(73, 73, 73)
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(33, 36, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txfIDClase, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txfNombreClase, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txfHorarioClase, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txfMaestro, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(39, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1);
        jPanel1.setBounds(200, 110, 620, 160);

        jLabel4.setBackground(new java.awt.Color(30, 47, 86));
        jLabel4.setFont(new java.awt.Font("Menlo", 1, 36)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Total a pagar:");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(320, 340, 400, 62);
        jLabel4.getAccessibleContext().setAccessibleDescription("");

        jLabel9.setFont(new java.awt.Font("Menlo", 1, 48)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(30, 47, 86));
        jLabel9.setText("FINALIZAR INSCRIPCIÓN");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(220, 40, 580, 62);

        jLabel10.setFont(new java.awt.Font("Menlo", 1, 48)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(30, 47, 86));
        jLabel10.setText("REALIZAR PAGO");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(300, 280, 400, 62);

        txfPrecio.setEditable(false);
        txfPrecio.setBackground(new java.awt.Color(30, 47, 86));
        txfPrecio.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        txfPrecio.setForeground(new java.awt.Color(255, 255, 255));
        txfPrecio.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txfPrecio.setText("jTextField1");
        txfPrecio.setBorder(null);
        txfPrecio.setOpaque(false);
        getContentPane().add(txfPrecio);
        txfPrecio.setBounds(580, 350, 120, 50);

        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Utilerias/botones/regresar.png"))); // NOI18N
        jButton4.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Utilerias/botones/regresarHovered.png"))); // NOI18N
        getContentPane().add(jButton4);
        jButton4.setBounds(380, 510, 256, 77);

        jButton1.setText("Pago Tarjeta");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(750, 420, 150, 40);

        b.setText("Pago Efectivo");
        getContentPane().add(b);
        b.setBounds(110, 420, 150, 40);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmClasesExistentes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmClasesExistentes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmClasesExistentes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmClasesExistentes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        List<DayOfWeek> dias = Arrays.asList(DayOfWeek.MONDAY, DayOfWeek.WEDNESDAY);
        ClaseDTO claseDTO = new ClaseDTO(1, "Contemporaneo", dias, LocalTime.MIN, LocalTime.MIN, "maestro", BigDecimal.ZERO);

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmFinalizarInscripcion(claseDTO).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton b;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txfHorarioClase;
    private javax.swing.JTextField txfIDClase;
    private javax.swing.JTextField txfMaestro;
    private javax.swing.JTextField txfNombreClase;
    private javax.swing.JTextField txfPrecio;
    // End of variables declaration//GEN-END:variables
}
