package FRMs;

import DTOs.GestionarClases.ClaseListaDTO;
import com.mycompany.dtos.AlumnoDTO;
import com.mycompany.dtos.ClaseDTO;
import com.mycompany.presentacion.ControlNavegacion;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Font;
import java.awt.Graphics;
import java.awt.Image;
import java.math.BigDecimal;
import java.time.DayOfWeek;
import java.time.format.DateTimeFormatter;
import java.util.List;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JPanel;
import org.netbeans.lib.awtextra.AbsoluteConstraints;
import org.netbeans.lib.awtextra.AbsoluteLayout;

/**
 *
 * @author daniel
 */
public class FrmFinalizarInscripcion extends javax.swing.JFrame {

    private Image imagenFondo;
    private AlumnoDTO alumno;
    private ClaseListaDTO claseLista;

    /**
     * Creates new customizer FrmFinalizarInscripcion
     */
    public FrmFinalizarInscripcion(ClaseListaDTO clase, AlumnoDTO alumno) {
        this.claseLista = clase;
        this.alumno = alumno;
        this.imagenFondo = new ImageIcon(getClass().getResource("/Utilerias/FondoCERO.jpeg")).getImage();

        // Panel con imagen de fondo
        JPanel pnlFondo = new JPanel() {
            @Override
            protected void paintComponent(Graphics g) {
                super.paintComponent(g);
                g.drawImage(imagenFondo, 0, 0, getWidth(), getHeight(), this);
            }
        };
        pnlFondo.setLayout(null); 

        setContentPane(pnlFondo);

        initComponents();

        // Configuración de la ventana
        setTitle("Finalizar Inscripción");
        setSize(1255, 759); 
        setLocationRelativeTo(null);

        configurarCampos(claseLista, alumno);
    }

    private void configurarCampos(ClaseListaDTO claseLista, AlumnoDTO alumno) {

        // Formato HTML centrado
        String nombreAlumno = "<html><div style='text-align: center;'>"
                + alumno.getNombreCompleto().replace(" ", "<br>")
                + "</div></html>";
        lblAlumno.setText(nombreAlumno);

        String nombreClase = "<html><div style='text-align: center;'>"
                + claseLista.getNombreClase().replace(" ", "<br>")
                + "</div></html>";
        lblNombreClase.setText(nombreClase);

        String horarioClase = "<html><div style='text-align: center;'>"
                + claseLista.getHorario().replace(" ", "<br>")
                + "</div></html>";
        lblHorario.setText(horarioClase);

        String nombreMaestro = "<html><div style='text-align: center;'>"
                + claseLista.getNombreMaestro().replace(" ", "<br>")
                + "</div></html>";
        lblMaestro.setText(nombreMaestro);

        String nombreAula = "<html><div style='text-align: center;'>"
                + claseLista.getNombreAula().replace(" ", "<br>")
                + "</div></html>";
        lblAula.setText(nombreAula);
//
        
        BigDecimal precio = this.claseLista.getPrecio();
        txtPrecio.setText(precio.toPlainString());

        // Aplicar estilos
        configurarLabelDatos(lblAlumno);
        configurarLabelDatos(lblNombreClase);
        configurarLabelDatos(lblHorario);
        configurarLabelDatos(lblMaestro);
        configurarLabelDatos(lblAula);
        
    }

    // configura los labels de los datos
    private void configurarLabelDatos(JLabel label) {
        label.setFont(new Font("Menlo", Font.PLAIN, 12));
        label.setForeground(Color.WHITE);
        label.setOpaque(true);
        label.setBackground(new Color(30, 47, 86));
        label.setPreferredSize(new Dimension(150, 40)); // Tamaño uniforme para datos
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the FormEditor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel4 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txtPrecio = new javax.swing.JTextField();
        btnRegresar = new javax.swing.JButton();
        btnPagoTarjeta = new javax.swing.JButton();
        btnPagoEfectivo = new javax.swing.JButton();
        PanelDatosClase = new javax.swing.JPanel();
        lblColumnAlumno = new javax.swing.JLabel();
        lblColumnClase = new javax.swing.JLabel();
        lblColumnHorario = new javax.swing.JLabel();
        lblColumnMaestro = new javax.swing.JLabel();
        lblColumnAula = new javax.swing.JLabel();
        lblAlumno = new javax.swing.JLabel();
        lblNombreClase = new javax.swing.JLabel();
        lblHorario = new javax.swing.JLabel();
        lblMaestro = new javax.swing.JLabel();
        lblAula = new javax.swing.JLabel();

        jLabel4.setBackground(new java.awt.Color(30, 47, 86));
        jLabel4.setFont(new java.awt.Font("Menlo", 1, 36)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Total a pagar:");

        jLabel9.setFont(new java.awt.Font("Menlo", 1, 55)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(30, 47, 86));
        jLabel9.setText("FINALIZAR INSCRIPCIÓN");

        jLabel10.setFont(new java.awt.Font("Menlo", 1, 48)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(30, 47, 86));
        jLabel10.setText("REALIZAR PAGO");

        txtPrecio.setEditable(false);
        txtPrecio.setBackground(new java.awt.Color(30, 47, 86));
        txtPrecio.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        txtPrecio.setForeground(new java.awt.Color(255, 255, 255));
        txtPrecio.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtPrecio.setText("jTextField1");
        txtPrecio.setBorder(null);
        txtPrecio.setOpaque(false);

        btnRegresar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Utilerias/botones/regresar.png"))); // NOI18N
        btnRegresar.setBorder(null);
        btnRegresar.setContentAreaFilled(false);
        btnRegresar.setOpaque(false);
        btnRegresar.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Utilerias/botones/regresarHovered.png"))); // NOI18N
        btnRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegresarActionPerformed(evt);
            }
        });

        btnPagoTarjeta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Utilerias/botones/btnPagoTarjeta.png"))); // NOI18N
        btnPagoTarjeta.setBorder(null);
        btnPagoTarjeta.setPreferredSize(new java.awt.Dimension(1280, 832));
        btnPagoTarjeta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPagoTarjetaActionPerformed(evt);
            }
        });

        btnPagoEfectivo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Utilerias/botones/btnPagoEfectivo.png"))); // NOI18N
        btnPagoEfectivo.setBorder(null);
        btnPagoEfectivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPagoEfectivoActionPerformed(evt);
            }
        });

        PanelDatosClase.setBackground(new java.awt.Color(30, 47, 86));
        PanelDatosClase.setForeground(new java.awt.Color(30, 47, 86));
        PanelDatosClase.setLayout(new java.awt.GridLayout(2, 5));

        lblColumnAlumno.setFont(new java.awt.Font("Menlo", 1, 14)); // NOI18N
        lblColumnAlumno.setForeground(new java.awt.Color(148, 197, 227));
        lblColumnAlumno.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblColumnAlumno.setText("ALUMNO");
        PanelDatosClase.add(lblColumnAlumno);

        lblColumnClase.setFont(new java.awt.Font("Menlo", 1, 14)); // NOI18N
        lblColumnClase.setForeground(new java.awt.Color(148, 197, 227));
        lblColumnClase.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblColumnClase.setText("CLASE");
        PanelDatosClase.add(lblColumnClase);

        lblColumnHorario.setFont(new java.awt.Font("Menlo", 1, 14)); // NOI18N
        lblColumnHorario.setForeground(new java.awt.Color(148, 197, 227));
        lblColumnHorario.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblColumnHorario.setText("HORARIO");
        PanelDatosClase.add(lblColumnHorario);

        lblColumnMaestro.setFont(new java.awt.Font("Menlo", 1, 14)); // NOI18N
        lblColumnMaestro.setForeground(new java.awt.Color(148, 197, 227));
        lblColumnMaestro.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblColumnMaestro.setText("MAESTRO");
        PanelDatosClase.add(lblColumnMaestro);

        lblColumnAula.setFont(new java.awt.Font("Menlo", 1, 14)); // NOI18N
        lblColumnAula.setForeground(new java.awt.Color(148, 197, 227));
        lblColumnAula.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblColumnAula.setText("AULA");
        PanelDatosClase.add(lblColumnAula);

        lblAlumno.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblAlumno.setForeground(new java.awt.Color(255, 255, 255));
        lblAlumno.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblAlumno.setText("jLabel1");
        PanelDatosClase.add(lblAlumno);

        lblNombreClase.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblNombreClase.setForeground(new java.awt.Color(255, 255, 255));
        lblNombreClase.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblNombreClase.setText("jLabel1");
        PanelDatosClase.add(lblNombreClase);

        lblHorario.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblHorario.setForeground(new java.awt.Color(255, 255, 255));
        lblHorario.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblHorario.setText("jLabel1");
        PanelDatosClase.add(lblHorario);

        lblMaestro.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblMaestro.setForeground(new java.awt.Color(255, 255, 255));
        lblMaestro.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblMaestro.setText("jLabel1");
        PanelDatosClase.add(lblMaestro);

        lblAula.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblAula.setForeground(new java.awt.Color(255, 255, 255));
        lblAula.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblAula.setText("jLabel1");
        PanelDatosClase.add(lblAula);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(310, 310, 310)
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 710, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(430, 430, 430)
                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(340, 340, 340)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(txtPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(160, 160, 160)
                        .addComponent(btnPagoEfectivo, javax.swing.GroupLayout.PREFERRED_SIZE, 450, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(70, 70, 70)
                        .addComponent(btnPagoTarjeta, javax.swing.GroupLayout.PREFERRED_SIZE, 380, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(510, 510, 510)
                        .addComponent(btnRegresar)))
                .addGap(0, 195, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(PanelDatosClase, javax.swing.GroupLayout.PREFERRED_SIZE, 725, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(235, 235, 235))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(48, 48, 48)
                .addComponent(PanelDatosClase, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(47, 47, 47)
                .addComponent(jLabel10)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(txtPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(48, 48, 48)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnPagoEfectivo, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnPagoTarjeta, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addComponent(btnRegresar)
                .addContainerGap(34, Short.MAX_VALUE))
        );

        jLabel4.getAccessibleContext().setAccessibleDescription("");
    }// </editor-fold>//GEN-END:initComponents

    private void btnPagoTarjetaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPagoTarjetaActionPerformed
        ControlNavegacion.mostrarPagoTarjeta(claseLista, alumno);
        this.dispose();
       
    }//GEN-LAST:event_btnPagoTarjetaActionPerformed

    private void btnPagoEfectivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPagoEfectivoActionPerformed
       ControlNavegacion.mostrarPagoEfectivo(claseLista, alumno);
       this.dispose();
      
    }//GEN-LAST:event_btnPagoEfectivoActionPerformed

    private void btnRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresarActionPerformed
        ControlNavegacion.mostrarDatosClase(claseLista);
        this.dispose();
    }//GEN-LAST:event_btnRegresarActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PanelDatosClase;
    private javax.swing.JButton btnPagoEfectivo;
    private javax.swing.JButton btnPagoTarjeta;
    private javax.swing.JButton btnRegresar;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel lblAlumno;
    private javax.swing.JLabel lblAula;
    private javax.swing.JLabel lblColumnAlumno;
    private javax.swing.JLabel lblColumnAula;
    private javax.swing.JLabel lblColumnClase;
    private javax.swing.JLabel lblColumnHorario;
    private javax.swing.JLabel lblColumnMaestro;
    private javax.swing.JLabel lblHorario;
    private javax.swing.JLabel lblMaestro;
    private javax.swing.JLabel lblNombreClase;
    private javax.swing.JTextField txtPrecio;
    // End of variables declaration//GEN-END:variables
}
