package FRMs;

import com.mycompany.presentacion.ControlNavegacion;
import com.mycompany.presentacion.excepciones.PresentacionException;
import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Graphics;
import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JPanel;
import org.netbeans.lib.awtextra.AbsoluteConstraints;
import org.netbeans.lib.awtextra.AbsoluteLayout;

/**
 *
 * @author daniel
 */
public class FrmInscribirClase extends javax.swing.JFrame {

    private Image imagenFondo;

    /**
     *
     *
     */
    public FrmInscribirClase() {
        initComponents();
        this.txfNombreClase.setForeground(Color.GRAY);
        this.txfNombreClase.setText("ingresa nombre clase...");
        this.setTitle("Inscribir Clase");

        this.imagenFondo = new ImageIcon(getClass().getResource("/Utilerias/FondoCERO.jpeg")).getImage();

        JPanel pnlFondo = new javax.swing.JPanel() {
            @Override
            protected void paintComponent(Graphics g) {
                super.paintComponent(g);
                g.drawImage(imagenFondo, 0, 0, getWidth(), getHeight(), this);
            }
        };

        getContentPane().setLayout(new AbsoluteLayout());
        pack();
        getContentPane().add(pnlFondo, new AbsoluteConstraints(0, 0, getWidth(), getHeight()));
        this.setLocationRelativeTo(null);
        this.setDefaultCloseOperation(EXIT_ON_CLOSE);

    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the FormEditor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txfNombreClase = new javax.swing.JTextField();
        botonBuscarClase = new javax.swing.JButton();
        btnRegresar = new javax.swing.JButton();

        setBackground(new java.awt.Color(148, 197, 227));
        setPreferredSize(new java.awt.Dimension(1280, 832));
        getContentPane().setLayout(null);

        jLabel9.setFont(new java.awt.Font("Menlo", 1, 24)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(30, 47, 86));
        jLabel9.setText("Nombre de la clase:");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(200, 370, 280, 62);

        jLabel10.setFont(new java.awt.Font("Menlo", 1, 55)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(30, 47, 86));
        jLabel10.setText("INSCRIBIR EN CLASE");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(340, 140, 640, 65);

        txfNombreClase.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        txfNombreClase.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txfNombreClase.setText("ingresa nombre clase...");
        txfNombreClase.setBorder(null);
        txfNombreClase.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txfNombreClaseMouseClicked(evt);
            }
        });
        txfNombreClase.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txfNombreClaseActionPerformed(evt);
            }
        });
        getContentPane().add(txfNombreClase);
        txfNombreClase.setBounds(500, 380, 580, 50);

        botonBuscarClase.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Utilerias/botones/btnBuscarClase.png"))); // NOI18N
        botonBuscarClase.setBorderPainted(false);
        botonBuscarClase.setContentAreaFilled(false);
        botonBuscarClase.setFocusPainted(false);
        botonBuscarClase.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonBuscarClaseActionPerformed(evt);
            }
        });
        getContentPane().add(botonBuscarClase);
        botonBuscarClase.setBounds(390, 540, 470, 90);

        btnRegresar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Utilerias/botones/btnVolverMenu.png"))); // NOI18N
        btnRegresar.setBorderPainted(false);
        btnRegresar.setContentAreaFilled(false);
        btnRegresar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnRegresar.setFocusPainted(false);
        btnRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegresarActionPerformed(evt);
            }
        });
        getContentPane().add(btnRegresar);
        btnRegresar.setBounds(420, 630, 420, 80);
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresarActionPerformed
        ControlNavegacion.mostrarMenuPrincipal();
        this.dispose();
    }//GEN-LAST:event_btnRegresarActionPerformed

    //BUSCAR CLASE BTN
    private void botonBuscarClaseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonBuscarClaseActionPerformed

        String campo = txfNombreClase.getText();
        ControlNavegacion.mostrarClasesExistente(campo);

    }//GEN-LAST:event_botonBuscarClaseActionPerformed

    private void txfNombreClaseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txfNombreClaseActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_txfNombreClaseActionPerformed

    private void txfNombreClaseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txfNombreClaseMouseClicked
        // TODO add your handling code here:
        txfNombreClase.setText("");
        txfNombreClase.setForeground(Color.BLACK);

    }//GEN-LAST:event_txfNombreClaseMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonBuscarClase;
    private javax.swing.JButton btnRegresar;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField txfNombreClase;
    // End of variables declaration//GEN-END:variables
}
