/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package FRMs;

import javax.swing.JFrame;
import java.awt.Color;
import java.awt.Graphics;
import java.awt.Image;
import java.awt.event.FocusEvent;
import java.awt.event.FocusListener;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JTextField;

/**
 *
 * @author Usuario
 */
public class FrmInscribirClase extends javax.swing.JFrame {
    private Image imagenFondo;
    /**
     * Creates new form FrmInscribirClase
     */
    public FrmInscribirClase() {
        initComponents();
        
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        
        this.setSize(1000, 700); // Ajusta el tamaño del JFrame
        this.setLocationRelativeTo(null); // Centra la ventana en la pantalla
        this.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);

        pack();
        this.setTitle("Inscribir Clase");
        this.imagenFondo = new ImageIcon(getClass().getResource("/Utilerias/FondoCERO.jpeg")).getImage();

        // Crear un JPanel con la imagen de fondo y agregarlo al frame
        JPanel jPanel1 = new JPanel() {
            @Override
            protected void paintComponent(Graphics g) {
                super.paintComponent(g);
                g.drawImage(imagenFondo, 0, 0, getWidth(), getHeight(), this);
            }
        };

        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 850, 550));
        configurarTxtNombreClase();
        pack();

    }

    private void configurarTxtNombreClase() {
        txtNombreClase.setText("Ingresa Nombre Clase...");
        txtNombreClase.setForeground(Color.GRAY);

        txtNombreClase.addMouseListener(new MouseAdapter() {
            private boolean clicked = false; // Variable para detectar el primer clic

            @Override
            public void mouseClicked(MouseEvent e) {
                if (!clicked) {
                    txtNombreClase.setText(""); // Borra el texto solo en el primer clic
                    txtNombreClase.setForeground(Color.BLACK);
                    clicked = true; // Evita que se borre en clics posteriores
                }
            }
        });
    }
    
    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtNombreClase = new javax.swing.JTextField();
        btnBuscarClase = new javax.swing.JButton();
        btnRegresar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Menlo", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(30, 47, 86));
        jLabel1.setText("Nombre de la clase:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 180, 230, 60));

        jLabel2.setFont(new java.awt.Font("Menlo", 1, 48)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(30, 47, 86));
        jLabel2.setText("INSCRIBIR EN CLASE");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 30, -1, -1));

        txtNombreClase.setBackground(new java.awt.Color(255, 255, 255));
        txtNombreClase.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        txtNombreClase.setForeground(new java.awt.Color(0, 0, 0));
        txtNombreClase.setText("ingresa nombre ");
        txtNombreClase.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        txtNombreClase.setOpaque(false);
        txtNombreClase.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreClaseActionPerformed(evt);
            }
        });
        getContentPane().add(txtNombreClase, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 190, 370, 40));

        btnBuscarClase.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Utilerias/botones/btnBuscarClase.png"))); // NOI18N
        btnBuscarClase.setBorderPainted(false);
        btnBuscarClase.setContentAreaFilled(false);
        btnBuscarClase.setFocusPainted(false);
        btnBuscarClase.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarClaseActionPerformed(evt);
            }
        });
        getContentPane().add(btnBuscarClase, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 310, -1, -1));

        btnRegresar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Utilerias/botones/btnRegresar.png"))); // NOI18N
        btnRegresar.setBorderPainted(false);
        btnRegresar.setContentAreaFilled(false);
        btnRegresar.setFocusPainted(false);
        btnRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegresarActionPerformed(evt);
            }
        });
        getContentPane().add(btnRegresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 420, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    //LOGICA BTN BUSCAR CLASE
    private void btnBuscarClaseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarClaseActionPerformed
        // TODO add your handling code here:
        String campo = txtNombreClase.getText();
        // Poner bucle si se cumple esta condicion
        if(campo == null || campo.trim().isEmpty() || campo.equalsIgnoreCase("ingresa nombre clase...")){
            JOptionPane.showMessageDialog(this, "El nombre de la clase no puede estar vacío o nulo", "Error", JOptionPane.ERROR_MESSAGE);
        }
        // IR A FRMCLASESEXISTENTES 
        
        
    }//GEN-LAST:event_btnBuscarClaseActionPerformed

    //LOGICA BTN REGRESAR
    private void btnRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresarActionPerformed
        // TODO add your handling code here:
        System.out.println("Regresar");
    }//GEN-LAST:event_btnRegresarActionPerformed

    private void txtNombreClaseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreClaseActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreClaseActionPerformed

        /**
         * @param args the command line arguments
         */
    public static void main(String args[]){
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmClasesExistentes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmClasesExistentes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmClasesExistentes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmClasesExistentes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmInscribirClase().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscarClase;
    private javax.swing.JButton btnRegresar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField txtNombreClase;
    // End of variables declaration//GEN-END:variables
}
