package FRMs;

import com.mycompany.presentacion.ControlNavegacion;
import com.mycompany.presentacion.excepciones.PresentacionException;
import java.awt.Color;
import java.awt.Graphics;
import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JPanel;

/**
 *
 * @author daniel
 */
public class FrmInscribirClase extends javax.swing.JFrame {

    private Image imagenFondo;
    private ControlNavegacion controlNav;

    /**
     * Creates new customizer FrmInscribirClase2
     */
    public FrmInscribirClase() {
        initComponents();
        controlNav = new ControlNavegacion();
        this.txfNombreClase.setForeground(Color.GRAY);
        this.txfNombreClase.setText("ingresa nombre clase...");
        this.setTitle("Inscribir Clase");

        // Cargar la imagen de fondo 
        this.imagenFondo = new ImageIcon(getClass().getResource("/Utilerias/FondoCERO.jpeg")).getImage();

        // Crear un JPanel con la imagen de fondo y lo agrega al frame
        JPanel jPanel1 = new javax.swing.JPanel() {
            @Override
            protected void paintComponent(Graphics g) {
                super.paintComponent(g);
                g.drawImage(imagenFondo, 0, 0, getWidth(), getHeight(), this);
            }
        };

        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 980, 552));

        this.setSize(1000, 700); // Ajusta el tamaño del JFrame
        this.setLocationRelativeTo(null); // Centra la ventana en la pantalla
        this.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        pack();
        //
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the FormEditor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txfNombreClase = new javax.swing.JTextField();
        botonBuscarClase = new javax.swing.JButton();
        btnRegresar = new javax.swing.JButton();

        getContentPane().setLayout(null);

        jLabel9.setFont(new java.awt.Font("Menlo", 1, 24)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(30, 47, 86));
        jLabel9.setText("Nombre de la clase:");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(100, 200, 280, 62);

        jLabel10.setFont(new java.awt.Font("Menlo", 1, 48)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(30, 47, 86));
        jLabel10.setText("INSCRIBIR EN CLASE");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(240, 50, 540, 62);

        txfNombreClase.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        txfNombreClase.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txfNombreClase.setText("ingresa nombre clase...");
        txfNombreClase.setBorder(null);
        txfNombreClase.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txfNombreClaseMouseClicked(evt);
            }
        });
        txfNombreClase.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txfNombreClaseActionPerformed(evt);
            }
        });
        getContentPane().add(txfNombreClase);
        txfNombreClase.setBounds(360, 210, 420, 50);

        botonBuscarClase.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Utilerias/botones/btnBuscarClase.png"))); // NOI18N
        botonBuscarClase.setBorderPainted(false);
        botonBuscarClase.setContentAreaFilled(false);
        botonBuscarClase.setFocusPainted(false);
        botonBuscarClase.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonBuscarClaseActionPerformed(evt);
            }
        });
        getContentPane().add(botonBuscarClase);
        botonBuscarClase.setBounds(250, 350, 470, 60);

        btnRegresar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Utilerias/botones/btnRegresar.png"))); // NOI18N
        btnRegresar.setBorderPainted(false);
        btnRegresar.setContentAreaFilled(false);
        btnRegresar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnRegresar.setFocusPainted(false);
        btnRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegresarActionPerformed(evt);
            }
        });
        getContentPane().add(btnRegresar);
        btnRegresar.setBounds(300, 460, 370, 60);
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnRegresarActionPerformed

    //BUSCAR CLASE BTN
    private void botonBuscarClaseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonBuscarClaseActionPerformed
        try {
            String campo = txfNombreClase.getText();
            controlNav.mostrarClasesExistentes(campo);
            this.dispose();
        } catch (PresentacionException ex) {
            controlNav.mostrarMensajeErrorConExcepcion(this, ex);
            txfNombreClase.setText("");
        }
        
        
    }//GEN-LAST:event_botonBuscarClaseActionPerformed

    private void txfNombreClaseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txfNombreClaseActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_txfNombreClaseActionPerformed

    private void txfNombreClaseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txfNombreClaseMouseClicked
        // TODO add your handling code here:
        txfNombreClase.setText("");
        txfNombreClase.setForeground(Color.BLACK);
        
    }//GEN-LAST:event_txfNombreClaseMouseClicked
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmClasesExistentes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmClasesExistentes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmClasesExistentes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmClasesExistentes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmInscribirClase().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonBuscarClase;
    private javax.swing.JButton btnRegresar;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField txfNombreClase;
    // End of variables declaration//GEN-END:variables
}
