
package FRMs;

import com.mycompany.presentacion.ControlNavegacion;
import java.awt.Graphics;
import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JPanel;
import org.netbeans.lib.awtextra.AbsoluteConstraints;
import org.netbeans.lib.awtextra.AbsoluteLayout;

/**
 * Pantalla que representa al menú principal del sistema
 * @author Usuario
 */
public class FrmMenuPrincipal extends javax.swing.JFrame {
    private Image imagenFondo;
    private ControlNavegacion controlNav;

    /**
     * Creates new form FrmMenuPrincipal
     */
    public FrmMenuPrincipal() {
        initComponents();
        this.setTitle("CERO");
        
        this.imagenFondo = new ImageIcon(getClass().getResource("/Utilerias/FondoCERO.jpeg")).getImage();

        JPanel pnlFondo = new javax.swing.JPanel() {
            @Override
            protected void paintComponent(Graphics g) {
                super.paintComponent(g);
                g.drawImage(imagenFondo, 0, 0, getWidth(), getHeight(), this);
            }
        };

        getContentPane().setLayout(new AbsoluteLayout());
        getContentPane().add(pnlFondo, new AbsoluteConstraints(0, 0, getWidth(), getHeight()));
        
        this.setLocationRelativeTo(null); 

        pack(); 
    
    }
    
    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        btnGaleriaProyectos = new javax.swing.JButton();
        btnGestionarClases = new javax.swing.JButton();
        btnInscribir = new javax.swing.JButton();
        btnGestionarAlumnos = new javax.swing.JButton();
        btnControlAsistencias = new javax.swing.JButton();
        btnInscribir4 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1280, 832));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Menlo", 1, 48)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(30, 47, 86));
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Utilerias/logoAzul.png"))); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 40, 530, 180));

        btnGaleriaProyectos.setBackground(null);
        btnGaleriaProyectos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Utilerias/botones/galeriaProyectos.png"))); // NOI18N
        btnGaleriaProyectos.setBorder(null);
        btnGaleriaProyectos.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnGaleriaProyectos.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Utilerias/botones/proyectosHovered.png"))); // NOI18N
        btnGaleriaProyectos.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Utilerias/botones/proyectosHovered.png"))); // NOI18N
        getContentPane().add(btnGaleriaProyectos, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 560, -1, -1));

        btnGestionarClases.setBackground(null);
        btnGestionarClases.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Utilerias/botones/GestionarClase.png"))); // NOI18N
        btnGestionarClases.setBorder(null);
        btnGestionarClases.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnGestionarClases.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Utilerias/botones/gestionarClasesHovered.png"))); // NOI18N
        getContentPane().add(btnGestionarClases, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 240, -1, -1));

        btnInscribir.setBackground(null);
        btnInscribir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Utilerias/botones/inscribirClase.png"))); // NOI18N
        btnInscribir.setBorder(null);
        btnInscribir.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnInscribir.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Utilerias/botones/inscribirClaseHovered.png"))); // NOI18N
        btnInscribir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInscribirActionPerformed(evt);
            }
        });
        getContentPane().add(btnInscribir, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 320, -1, -1));

        btnGestionarAlumnos.setBackground(null);
        btnGestionarAlumnos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Utilerias/botones/gestionarAlumnos.png"))); // NOI18N
        btnGestionarAlumnos.setBorder(null);
        btnGestionarAlumnos.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnGestionarAlumnos.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Utilerias/botones/gestionarAlumnosHovered.png"))); // NOI18N
        getContentPane().add(btnGestionarAlumnos, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 480, -1, -1));

        btnControlAsistencias.setBackground(null);
        btnControlAsistencias.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Utilerias/botones/controlAsistencias.png"))); // NOI18N
        btnControlAsistencias.setBorder(null);
        btnControlAsistencias.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnControlAsistencias.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Utilerias/botones/asistenciasHovered.png"))); // NOI18N
        btnControlAsistencias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnControlAsistenciasActionPerformed(evt);
            }
        });
        getContentPane().add(btnControlAsistencias, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 400, -1, -1));

        btnInscribir4.setBackground(null);
        btnInscribir4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Utilerias/botones/cerrarSesion.png"))); // NOI18N
        btnInscribir4.setBorder(null);
        btnInscribir4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnInscribir4.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Utilerias/botones/cerrarSesionHovered.png"))); // NOI18N
        getContentPane().add(btnInscribir4, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 670, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnInscribirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInscribirActionPerformed
        ControlNavegacion.mostrarInscribirClase();
        this.dispose();
    }//GEN-LAST:event_btnInscribirActionPerformed

    private void btnControlAsistenciasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnControlAsistenciasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnControlAsistenciasActionPerformed

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnControlAsistencias;
    private javax.swing.JButton btnGaleriaProyectos;
    private javax.swing.JButton btnGestionarAlumnos;
    private javax.swing.JButton btnGestionarClases;
    private javax.swing.JButton btnInscribir;
    private javax.swing.JButton btnInscribir4;
    private javax.swing.JLabel jLabel3;
    // End of variables declaration//GEN-END:variables
}
