
package FRMs;

import com.mycompany.infraestructura.sistemaPago.implementaciones.NuevoPagoTarjetaDTO;
import com.mycompany.infraestructura.sistemaPago.implementaciones.PagoRealizadoDTO;
import com.mycompany.negocio.dtos.AlumnoDTO;
import com.mycompany.negocio.dtos.ClaseDTO;
import com.mycompany.negocio.dtos.InscripcionDTO;
import com.mycompany.negocio.dtos.NuevaInscripcionDTO;
import com.mycompany.negocio.dtos.NuevoPagoDTO;
import com.mycompany.negocio.dtos.PagoDTO;
import com.mycompany.negocio.dtos.PagoTarjetaDTO;
import com.mycompany.presentacion.ControlNavegacion;
import com.toedter.calendar.JDateChooser;
import java.awt.Color;
import java.awt.Graphics;
import java.awt.Image;
import java.math.BigDecimal;
import java.time.LocalDate;
import java.time.LocalDateTime;
import java.time.ZoneId;
import java.util.Date;
import javax.swing.ImageIcon;
import javax.swing.JPanel;

/**
 *
 * @author Usuario
 */
public class FrmPagoTarjeta extends javax.swing.JFrame {
    private Image imagenFondo;
    private ClaseDTO clase;
    private AlumnoDTO alumno;
    private JDateChooser fechaVencimiento;

    /**
     * Creates new form FrmMenuPrincipal
     */
    public FrmPagoTarjeta(ClaseDTO clase, AlumnoDTO alumno) {
        initComponents();
        this.clase = clase;
        this.alumno = alumno;
        this.setTitle("Pago con tarjeta");
        
        // Cargar la imagen de fondo 
        this.imagenFondo = new ImageIcon(getClass().getResource("/Utilerias/FondoCERO.jpeg")).getImage();

        // Crear un JPanel con la imagen de fondo y lo agrega al frame
        JPanel jPanel1 = new javax.swing.JPanel() {
            @Override
            protected void paintComponent(Graphics g) {
                super.paintComponent(g);
                g.drawImage(imagenFondo, 0, 0, getWidth(), getHeight(), this);
            }
        };

        jPanel1.setLayout(null); // Permite posicionar manualmente los componentes
        jPanel1.setBounds(0, 0, 800, 700);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 700));

        // Agregar JDateChooser dentro del JPanel
        fechaVencimiento = new JDateChooser();
        jPanel1.add(fechaVencimiento);
        
        fechaVencimiento.setBounds(440, 330, 290, 30); // (x, y, ancho, alto)

        this.setSize(800, 700); // Ajusta el tamaño del JFrame
        this.setLocationRelativeTo(null); // Centra la ventana en la pantalla

    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtCvv = new javax.swing.JTextField();
        btnRegresar = new javax.swing.JButton();
        btnRealizarPago = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtNumeroCuenta = new javax.swing.JTextField();
        txtPropietario = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Menlo", 1, 48)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(30, 47, 86));
        jLabel3.setText("DATOS DE TARJETA");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 60, -1, -1));

        jLabel4.setFont(new java.awt.Font("Menlo", 1, 30)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("CVV: ");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 390, -1, -1));

        jLabel5.setFont(new java.awt.Font("Menlo", 1, 30)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Número de cuenta:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 190, -1, -1));

        txtCvv.setFont(new java.awt.Font("Helvetica Neue", 1, 30)); // NOI18N
        txtCvv.setForeground(new java.awt.Color(153, 153, 153));
        txtCvv.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        txtCvv.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        txtCvv.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtCvvMousePressed(evt);
            }
        });
        getContentPane().add(txtCvv, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 390, 290, -1));

        btnRegresar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Utilerias/botones/regresar.png"))); // NOI18N
        btnRegresar.setBorder(null);
        btnRegresar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnRegresar.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Utilerias/botones/regresarHovered.png"))); // NOI18N
        getContentPane().add(btnRegresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 590, -1, -1));

        btnRealizarPago.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Utilerias/botones/realizarPago.png"))); // NOI18N
        btnRealizarPago.setBorder(null);
        btnRealizarPago.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnRealizarPago.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Utilerias/botones/realizarPagoHovered.png"))); // NOI18N
        btnRealizarPago.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRealizarPagoActionPerformed(evt);
            }
        });
        getContentPane().add(btnRealizarPago, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 500, -1, -1));

        jLabel7.setFont(new java.awt.Font("Menlo", 1, 30)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Propietario:");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 250, -1, -1));

        jLabel8.setFont(new java.awt.Font("Menlo", 1, 30)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Fecha de expiración:");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 320, -1, -1));

        txtNumeroCuenta.setFont(new java.awt.Font("Helvetica Neue", 1, 30)); // NOI18N
        txtNumeroCuenta.setForeground(new java.awt.Color(153, 153, 153));
        txtNumeroCuenta.setBorder(null);
        txtNumeroCuenta.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        txtNumeroCuenta.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtNumeroCuentaMousePressed(evt);
            }
        });
        getContentPane().add(txtNumeroCuenta, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 190, 290, -1));

        txtPropietario.setFont(new java.awt.Font("Helvetica Neue", 1, 30)); // NOI18N
        txtPropietario.setForeground(new java.awt.Color(153, 153, 153));
        txtPropietario.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        txtPropietario.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        txtPropietario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtPropietarioMousePressed(evt);
            }
        });
        getContentPane().add(txtPropietario, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 250, 290, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtCvvMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtCvvMousePressed

        txtCvv.setForeground(Color.BLACK);
    }//GEN-LAST:event_txtCvvMousePressed

    private void txtNumeroCuentaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtNumeroCuentaMousePressed

        txtNumeroCuenta.setForeground(Color.BLACK);
    }//GEN-LAST:event_txtNumeroCuentaMousePressed

    private void txtPropietarioMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtPropietarioMousePressed

        txtPropietario.setForeground(Color.BLACK);
    }//GEN-LAST:event_txtPropietarioMousePressed

    private void btnRealizarPagoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRealizarPagoActionPerformed
        // validar datos
        
        String numeroCuenta = txtNumeroCuenta.getText();
        String propietario = txtPropietario.getText();
        Date fechaSeleccionada = fechaVencimiento.getDate();
        Integer cvv = Integer.valueOf(txtCvv.getText());
        LocalDate fechaVencimiento = fechaSeleccionada.toInstant().atZone(ZoneId.systemDefault()).toLocalDate();

        // validar datos
        if(!ControlNavegacion.getInscribirClase().validarNumeroCuenta(numeroCuenta)){
            ControlNavegacion.mostrarMensajeErrorNumeroCuentaInvalido(this);
        }
        
        if(!ControlNavegacion.getInscribirClase().validarPropietarioTarjeta(propietario)){
            ControlNavegacion.mostrarMensajeErrorPropietarioTarjetaInvalido(this);
        }
        
        if(!ControlNavegacion.getInscribirClase().validarFechaExpiracion(fechaVencimiento)){
            ControlNavegacion.mostrarMensajeFechaVencimientoInvalida(this);
        }
        
        if(!ControlNavegacion.getInscribirClase().validarCVV(cvv)){
            ControlNavegacion.mostrarMensajeErrorCVVInvalido(this);
        }

        BigDecimal monto = clase.getPrecio();
        
        // armar nuevopagoTarjetaDTo
        NuevoPagoTarjetaDTO nuevoPago = new NuevoPagoTarjetaDTO(numeroCuenta, propietario, fechaVencimiento, cvv, monto);
        
        PagoRealizadoDTO pagoRealizado = ControlNavegacion.getInscribirClase().confirmarPagoTarjeta(nuevoPago);
        // enviarlo al control
        
        PagoTarjetaDTO pagoTarjeta = new PagoTarjetaDTO(pagoRealizado.getCodigoConfirmacion(), pagoRealizado.getFechaHora());
        NuevoPagoDTO nuevoPagoDTO = new NuevoPagoDTO(monto, pagoTarjeta);
        PagoDTO pago = ControlNavegacion.getInscribirClase().realizarPagoTarjeta(nuevoPagoDTO);

        if (pago != null) {
            //crear nuevainscripciondto
            LocalDateTime fechaActual = LocalDateTime.now();
            NuevaInscripcionDTO inscripcion = new NuevaInscripcionDTO(clase, alumno, fechaActual, pago);
            InscripcionDTO inscripcionRealizada = ControlNavegacion.getInscribirClase().realizarInscripcion(inscripcion);

            if (inscripcionRealizada != null) {
                ControlNavegacion.mostrarMensajePagoExitoso(this);
            }

 
        }
    }//GEN-LAST:event_btnRealizarPagoActionPerformed

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRealizarPago;
    private javax.swing.JButton btnRegresar;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JTextField txtCvv;
    private javax.swing.JTextField txtNumeroCuenta;
    private javax.swing.JTextField txtPropietario;
    // End of variables declaration//GEN-END:variables
}
