
package FRMs;

import com.mycompany.dtos.AlumnoDTO;
import com.mycompany.dtos.ClaseDTO;
import com.mycompany.dtos.NuevoPagoDTO;
import com.mycompany.dtos.PagoEfectivoDTO;
import com.mycompany.presentacion.ControlNavegacion;
import com.mycompany.presentacion.excepciones.PresentacionException;
import java.awt.Color;
import java.awt.Graphics;
import java.awt.Image;
import java.math.BigDecimal;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import org.netbeans.lib.awtextra.AbsoluteConstraints;
import org.netbeans.lib.awtextra.AbsoluteLayout;

/**
 *
 * @author victoria
 */
public class FrmPagoEfectivo extends javax.swing.JFrame {
    private Image imagenFondo;
    private ClaseDTO clase;
    private AlumnoDTO alumno;
    

    /**
     * Creates new form FrmMenuPrincipal
     * @param clase clase a la que se está realizando la inscripcion
     */
    public FrmPagoEfectivo(ClaseDTO clase, AlumnoDTO alumno) {
        initComponents();
        this.clase = clase;
        this.alumno = alumno;
        this.setTitle("Pago en efectivo");
        lblTotalPago.setText(clase.getPrecio().toString());
        
      
        this.imagenFondo = new ImageIcon(getClass().getResource("/Utilerias/FondoCERO.jpeg")).getImage();
       JPanel pnlFondo = new javax.swing.JPanel() {
            @Override
            protected void paintComponent(Graphics g) {
                super.paintComponent(g);
                g.drawImage(imagenFondo, 0, 0, getWidth(), getHeight(), this);
            }
        };

        getContentPane().setLayout(new AbsoluteLayout());
        pack();
        getContentPane().add(pnlFondo, new AbsoluteConstraints(0, 0, getWidth(), getHeight()));
        this.setLocationRelativeTo(null);
    
    }
    
    private void limpiarCampos(){
        this.txtEfectivoRecibido.setText("");
        this.lblCambio.setText("0.0");
    }
    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblCambio = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtEfectivoRecibido = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        lblTotalPago = new javax.swing.JLabel();
        btnRegresar = new javax.swing.JButton();
        btnCalcularCambio = new javax.swing.JButton();
        btnRealizarPago = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1080, 832));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblCambio.setFont(new java.awt.Font("Menlo", 1, 30)); // NOI18N
        lblCambio.setForeground(new java.awt.Color(255, 255, 255));
        lblCambio.setText("0.00");
        getContentPane().add(lblCambio, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 356, 230, 40));

        jLabel3.setFont(new java.awt.Font("Menlo", 1, 55)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(30, 47, 86));
        jLabel3.setText("PAGO EN EFECTIVO");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 115, -1, 60));

        jLabel4.setFont(new java.awt.Font("Menlo", 1, 30)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Cantidad recibida: ");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 286, -1, 40));

        jLabel5.setFont(new java.awt.Font("Menlo", 1, 30)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Total a pagar: ");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 216, -1, 40));

        jLabel6.setFont(new java.awt.Font("Menlo", 1, 30)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Cambio: ");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 356, -1, 40));

        txtEfectivoRecibido.setFont(new java.awt.Font("Helvetica Neue", 1, 30)); // NOI18N
        txtEfectivoRecibido.setForeground(new java.awt.Color(153, 153, 153));
        txtEfectivoRecibido.setText("0.00");
        txtEfectivoRecibido.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        txtEfectivoRecibido.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        txtEfectivoRecibido.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtEfectivoRecibidoMousePressed(evt);
            }
        });
        getContentPane().add(txtEfectivoRecibido, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 290, 140, 40));
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 330, 140, 10));

        lblTotalPago.setFont(new java.awt.Font("Menlo", 1, 30)); // NOI18N
        lblTotalPago.setForeground(new java.awt.Color(255, 255, 255));
        lblTotalPago.setText("0.00");
        getContentPane().add(lblTotalPago, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 216, 200, 40));

        btnRegresar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Utilerias/botones/regresar.png"))); // NOI18N
        btnRegresar.setBorder(null);
        btnRegresar.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Utilerias/botones/regresarHovered.png"))); // NOI18N
        btnRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegresarActionPerformed(evt);
            }
        });
        getContentPane().add(btnRegresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 640, -1, 70));

        btnCalcularCambio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Utilerias/botones/calcularCambio.png"))); // NOI18N
        btnCalcularCambio.setBorder(null);
        btnCalcularCambio.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Utilerias/botones/calcularCambioHovered.png"))); // NOI18N
        btnCalcularCambio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalcularCambioActionPerformed(evt);
            }
        });
        getContentPane().add(btnCalcularCambio, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 458, -1, 70));

        btnRealizarPago.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Utilerias/botones/realizarPago.png"))); // NOI18N
        btnRealizarPago.setBorder(null);
        btnRealizarPago.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Utilerias/botones/realizarPagoHovered.png"))); // NOI18N
        btnRealizarPago.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRealizarPagoActionPerformed(evt);
            }
        });
        getContentPane().add(btnRealizarPago, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 547, -1, 70));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtEfectivoRecibidoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtEfectivoRecibidoMousePressed
        txtEfectivoRecibido.setText(" ");
        txtEfectivoRecibido.setForeground(Color.BLACK);
    }//GEN-LAST:event_txtEfectivoRecibidoMousePressed

    private void btnCalcularCambioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalcularCambioActionPerformed
        String textoEfectivo = txtEfectivoRecibido.getText();
        if (textoEfectivo.isEmpty()) {
            JOptionPane.showMessageDialog(this, "El campo de efectivo recibido no puede estar vacío.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        BigDecimal cambio;

        cambio = ControlNavegacion.calcularCambio(clase.getPrecio(), new BigDecimal(textoEfectivo), this);
        lblCambio.setText(cambio.toString());

    }//GEN-LAST:event_btnCalcularCambioActionPerformed

    private void btnRealizarPagoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRealizarPagoActionPerformed
        //hacer pagoefectivodto
        PagoEfectivoDTO pagoEfectivo = new PagoEfectivoDTO(new BigDecimal(txtEfectivoRecibido.getText()), new BigDecimal(lblCambio.getText()));
        // armar nuevopagodto
        NuevoPagoDTO nuevoPago = new NuevoPagoDTO(clase.getPrecio(), pagoEfectivo);
        ControlNavegacion.realizarPagoEfectivo(nuevoPago, clase, alumno, this);
        ControlNavegacion.mostrarMensajePagoExitoso(this);
        
    }//GEN-LAST:event_btnRealizarPagoActionPerformed

    private void btnRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresarActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnRegresarActionPerformed

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCalcularCambio;
    private javax.swing.JButton btnRealizarPago;
    private javax.swing.JButton btnRegresar;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lblCambio;
    private javax.swing.JLabel lblTotalPago;
    private javax.swing.JTextField txtEfectivoRecibido;
    // End of variables declaration//GEN-END:variables
}
